enum Move {
  Absorb = "Absorb",
  Acid = "Acid",
  AcidArmor = "Acid Armor",
  AerialAce = "Aerial Ace",
  Agility = "Agility",
  AirCutter = "Air Cutter",
  Amnesia = "Amnesia",
  ArmThrust = "Arm Thrust",
  AuroraBeam = "Aurora Beam",
  Aromatherapy = "Aromatherapy",
  Assist = "Assist",
  Astonish = "Astonish",
  Barrage = "Barrage",
  Barrier = "Barrier",
  Bide = "Bide",
  Bind = "Bind",
  BlastBurn = "Blast Burn",
  BlazeKick = "Blaze Kick",
  Block = "Block",
  Blizzard = "Blizzard",
  BodySlam = "Body Slam",
  BoneClub = "Bone Club",
  Bonemerang = "Bonemerang",
  Bounce = "Bounce",
  BrickBreak = "Brick Break",
  Bubble = "Bubble",
  BubbleBeam = "Bubble Beam",
  BulkUp = "Bulk Up",
  BulletSeed = "Bullet Seed",
  CalmMind = "Calm Mind",
  Camouflage = "Camouflage",
  Charge = "Charge",
  Clamp = "Clamp",
  ConfuseRay = "Confuse Ray",
  Confusion = "Confusion",
  Constrict = "Constrict",
  Conversion = "Conversion",
  Counter = "Counter",
  CometPunch = "Comet Punch",
  CosmicPower = "Cosmic Power",
  Covet = "Covet",
  Crabhammer = "Crabhammer",
  CrushClaw = "Crush Claw",
  Cut = "Cut",
  DefenseCurl = "Defense Curl",
  Dig = "Dig",
  Disable = "Disable",
  Dive = "Dive",
  DizzyPunch = "Dizzy Punch",
  DoomDesire = "Doom Desire",
  DragonClaw = "Dragon Claw",
  DragonDance = "Dragon Dance",
  DoubleKick = "Double Kick",
  DoubleSlap = "Double Slap",
  DoubleTeam = "Double Team",
  DoubleEdge = "Double-Edge",
  DragonRage = "Dragon Rage",
  DreamEater = "Dream Eater",
  DrillPeck = "Drill Peck",
  Earthquake = "Earthquake",
  EggBomb = "Egg Bomb",
  Endeavor = "Endeavor",
  Ember = "Ember",
  Eruption = "Eruption",
  Explosion = "Explosion",
  Facade = "Facade",
  FakeOut = "Fake Out",
  FakeTears = "Fake Tears",
  FeatherDance = "Feather Dance",
  FireBlast = "Fire Blast",
  FirePunch = "Fire Punch",
  FireSpin = "Fire Spin",
  Flatter = "Flatter",
  Flamethrower = "Flamethrower",
  Flash = "Flash",
  Fly = "Fly",
  FocusEnergy = "Focus Energy",
  FocusPunch = "Focus Punch",
  FollowMe = "Follow Me",
  FrenzyPlant = "Frenzy Plant",
  FuryAttack = "Fury Attack",
  FurySwipes = "Fury Swipes",
  Glare = "Glare",
  GrassWhistle = "Grass Whistle",
  Growl = "Growl",
  Growth = "Growth",
  Grudge = "Grudge",
  Guillotine = "Guillotine",
  Gust = "Gust",
  Harden = "Harden",
  Hail = "Hail",
  Haze = "Haze",
  Headbutt = "Headbutt",
  HeatWave = "Heat Wave",
  HelpingHand = "Helping Hand",
  Howl = "Howl",
  HighJumpKick = "High Jump Kick",
  HornAttack = "Horn Attack",
  HornDrill = "Horn Drill",
  HydroCannon = "Hydro Cannon",
  HydroPump = "Hydro Pump",
  HyperBeam = "Hyper Beam",
  HyperFang = "Hyper Fang",
  HyperVoice = "Hyper Voice",
  Hypnosis = "Hypnosis",
  IceBall = "Ice Ball",
  IceBeam = "Ice Beam",
  IcePunch = "Ice Punch",
  IcicleSpear = "Icicle Spear",
  Imprison = "Imprison",
  Ingrain = "Ingrain",
  IronDefense = "Iron Defense",
  JumpKick = "Jump Kick",
  KarateChop = "Karate Chop",
  Kinesis = "Kinesis",
  KnockOff = "Knock Off",
  LeafBlade = "Leaf Blade",
  LeechLife = "Leech Life",
  LeechSeed = "Leech Seed",
  Leer = "Leer",
  Lick = "Lick",
  LightScreen = "Light Screen",
  LovelyKiss = "Lovely Kiss",
  LowKick = "Low Kick",
  LusterPurge = "Luster Purge",
  MagicCoat = "Magic Coat",
  MagicalLeaf = "Magical Leaf",
  Meditate = "Meditate",
  MegaDrain = "Mega Drain",
  MegaKick = "Mega Kick",
  MegaPunch = "Mega Punch",
  Memento = "Memento",
  MetalSound = "Metal Sound",
  MeteorMash = "Meteor Mash",
  Metronome = "Metronome",
  Mimic = "Mimic",
  Minimize = "Minimize",
  MirrorMove = "Mirror Move",
  Mist = "Mist",
  MistBall = "Mist Ball",
  MudShot = "Mud Shot",
  MudSport = "Mud Sport",
  MuddyWater = "Muddy Water",
  NaturePower = "Nature Power",
  NeedleArm = "Needle Arm",
  NightShade = "Night Shade",
  OdorSleuth = "Odor Sleuth",
  Overheat = "Overheat",
  PayDay = "Pay Day",
  Peck = "Peck",
  PetalDance = "Petal Dance",
  PinMissile = "Pin Missile",
  PoisonFang = "Poison Fang",
  PoisonGas = "Poison Gas",
  PoisonPowder = "Poison Powder",
  PoisonSting = "Poison Sting",
  PoisonTail = "Poison Tail",
  Pound = "Pound",
  Psybeam = "Psybeam",
  PsychoBoost = "Psycho Boost",
  Psychic = "Psychic",
  Psywave = "Psywave",
  QuickAttack = "Quick Attack",
  Rage = "Rage",
  RazorLeaf = "Razor Leaf",
  RazorWind = "Razor Wind",
  Recover = "Recover",
  Recycle = "Recycle",
  Reflect = "Reflect",
  Refresh = "Refresh",
  Rest = "Rest",
  Revenge = "Revenge",
  Roar = "Roar",
  RockBlast = "Rock Blast",
  RockSlide = "Rock Slide",
  RockThrow = "Rock Throw",
  RockTomb = "Rock Tomb",
  RolePlay = "Role Play",
  RollingKick = "Rolling Kick",
  SandAttack = "Sand Attack",
  SandTomb = "Sand Tomb",
  Scratch = "Scratch",
  Screech = "Screech",
  SecretPower = "Secret Power",
  SeismicToss = "Seismic Toss",
  SelfDestruct = "Self-Destruct",
  ShadowPunch = "Shadow Punch",
  Sharpen = "Sharpen",
  Sing = "Sing",
  SheerCold = "Sheer Cold",
  ShockWave = "Shock Wave",
  SignalBeam = "Signal Beam",
  SilverWind = "Silver Wind",
  SkillSwap = "Skill Swap",
  SkullBash = "Skull Bash",
  SkyAttack = "Sky Attack",
  SkyUppercut = "Sky Uppercut",
  SlackOff = "Slack Off",
  Slam = "Slam",
  Slash = "Slash",
  SleepPowder = "Sleep Powder",
  Sludge = "Sludge",
  SmellingSalts = "Smelling Salts",
  Smog = "Smog",
  Smokescreen = "Smokescreen",
  Snatch = "Snatch",
  SoftBoiled = "Soft-Boiled",
  SolarBeam = "Solar Beam",
  SonicBoom = "Sonic Boom",
  SpikeCannon = "Spike Cannon",
  SpitUp = "Spit Up",
  Splash = "Splash",
  Spore = "Spore",
  Stomp = "Stomp",
  Stockpile = "Stockpile",
  Strength = "Strength",
  StringShot = "String Shot",
  Struggle = "Struggle",
  StunSpore = "Stun Spore",
  Submission = "Submission",
  Substitute = "Substitute",
  SuperFang = "Super Fang",
  Superpower = "Superpower",
  Supersonic = "Supersonic",
  Surf = "Surf",
  Swallow = "Swallow",
  Swift = "Swift",
  SwordsDance = "Swords Dance",
  Tackle = "Tackle",
  TailGlow = "Tail Glow",
  TailWhip = "Tail Whip",
  TakeDown = "Take Down",
  Taunt = "Taunt",
  TeeterDance = "Teeter Dance",
  Teleport = "Teleport",
  Thrash = "Thrash",
  Thunder = "Thunder",
  ThunderPunch = "Thunder Punch",
  ThunderShock = "Thunder Shock",
  ThunderWave = "Thunder Wave",
  Thunderbolt = "Thunderbolt",
  Tickle = "Tickle",
  Torment = "Torment",
  Toxic = "Toxic",
  Transform = "Transform",
  Trick = "Trick",
  TriAttack = "Tri Attack",
  Twineedle = "Twineedle",
  Uproar = "Uproar",
  VineWhip = "Vine Whip",
  ViseGrip = "Vise Grip",
  VoltTackle = "Volt Tackle",
  WaterGun = "Water Gun",
  WaterPulse = "Water Pulse",
  WaterSport = "Water Sport",
  WaterSpout = "Water Spout",
  Waterfall = "Waterfall",
  WeatherBall = "Weather Ball",
  Whirlwind = "Whirlwind",
  WillOWisp = "Will-O-Wisp",
  WingAttack = "Wing Attack",
  Wish = "Wish",
  Withdraw = "Withdraw",
  Wrap = "Wrap",
  Yawn = "Yawn",
}

enum MoveCategory {
  Physical = "Physical",
  Special = "Special",
  Status = "Status",
}

enum Type {
  Normal = "Normal",
  Fighting = "Fighting",
  Flying = "Flying",
  Poison = "Poison",
  Ground = "Ground",
  Rock = "Rock",
  Bug = "Bug",
  Ghost = "Ghost",
  Steel = "Steel",
  Fire = "Fire",
  Water = "Water",
  Grass = "Grass",
  Electric = "Electric",
  Psychic = "Psychic",
  Ice = "Ice",
  Dragon = "Dragon",
  Dark = "Dark",
  Fairy = "Fairy",
}

type MoveDetails = {
  accuracy: number | null;
  basePower: number | null;
  category: MoveCategory;
  name: string;
  pp: number;
  priority: number;
  type: Type;
  description: string;
};

export const moves: Record<Move, MoveDetails> = {
  [Move.Absorb]: {
    accuracy: 100,
    basePower: 20,
    category: MoveCategory.Special,
    name: "Absorb",
    pp: 25,
    priority: 0,
    type: Type.Grass,
    description: "User recovers half the HP inflicted on opponent.",
  },
  [Move.Acid]: {
    accuracy: 100,
    basePower: 40,
    category: MoveCategory.Special,
    name: "Acid",
    pp: 30,
    priority: 0,
    type: Type.Poison,
    description:
      "Has a 10% chance to lower the target's Special Defense by one stage.",
  },
  [Move.AcidArmor]: {
    accuracy: null,
    basePower: null,
    category: MoveCategory.Status,
    name: "Acid Armor",
    pp: 20,
    priority: 0,
    type: Type.Poison,
    description: "Raises the user's Defense by two stages.",
  },
  [Move.AerialAce]: {
    accuracy: 100,
    basePower: 60,
    category: MoveCategory.Physical,
    name: "Aerial Ace",
    pp: 20,
    priority: 0,
    type: Type.Flying,
    description: "Ignores accuracy and evasion modifiers.",
  },
  [Move.Agility]: {
    accuracy: null,
    basePower: null,
    category: MoveCategory.Status,
    name: "Agility",
    pp: 30,
    priority: 0,
    type: Type.Psychic,
    description: "Raises the user's Speed by two stages.",
  },
  [Move.AirCutter]: {
    accuracy: 95,
    basePower: 55,
    category: MoveCategory.Special,
    name: "Air Cutter",
    pp: 25,
    priority: 0,
    type: Type.Flying,
    description: "Has a 30% chance to make the target flinch.",
  },
  [Move.Amnesia]: {
    accuracy: null,
    basePower: null,
    category: MoveCategory.Status,
    name: "Amnesia",
    pp: 20,
    priority: 0,
    type: Type.Psychic,
    description: "Raises the user's Special Defense by two stages.",
  },
  [Move.ArmThrust]: {
    accuracy: 100,
    basePower: 15,
    category: MoveCategory.Physical,
    name: "Arm Thrust",
    pp: 20,
    priority: 0,
    type: Type.Fighting,
    description: "Hits 2-5 times in one turn.",
  },
  [Move.AuroraBeam]: {
    accuracy: 100,
    basePower: 65,
    category: MoveCategory.Special,
    name: "Aurora Beam",
    pp: 20,
    priority: 0,
    type: Type.Ice,
    description: "Has a 10% chance to lower the target's Attack by one stage.",
  },
  [Move.Aromatherapy]: {
    accuracy: null,
    basePower: null,
    category: MoveCategory.Status,
    name: "Aromatherapy",
    pp: 5,
    priority: 0,
    type: Type.Grass,
    description: "Cures the user and its allies of all status conditions.",
  },
  [Move.Assist]: {
    accuracy: null,
    basePower: null,
    category: MoveCategory.Status,
    name: "Assist",
    pp: 20,
    priority: 0,
    type: Type.Normal,
    description: "Randomly selects and uses any move in the user's party.",
  },
  [Move.Astonish]: {
    accuracy: 100,
    basePower: 30,
    category: MoveCategory.Physical,
    name: "Astonish",
    pp: 15,
    priority: 0,
    type: Type.Ghost,
    description: "Has a 30% chance to make the target flinch.",
  },
  [Move.Barrage]: {
    accuracy: 85,
    basePower: 15,
    category: MoveCategory.Physical,
    name: "Barrage",
    pp: 20,
    priority: 0,
    type: Type.Normal,
    description: "Hits 2-5 times in one turn.",
  },
  [Move.Barrier]: {
    accuracy: null,
    basePower: null,
    category: MoveCategory.Status,
    name: "Barrier",
    pp: 20,
    priority: 0,
    type: Type.Psychic,
    description: "Raises the user's Defense by two stages.",
  },
  [Move.Bide]: {
    accuracy: null,
    basePower: null,
    category: MoveCategory.Physical,
    name: "Bide",
    pp: 10,
    priority: 1,
    type: Type.Normal,
    description: "The user takes damage for 2 turns, then strikes back double.",
  },
  [Move.Bind]: {
    accuracy: 85,
    basePower: 15,
    category: MoveCategory.Physical,
    name: "Bind",
    pp: 20,
    priority: 0,
    type: Type.Normal,
    description: "Traps the target for 4-5 turns.",
  },
  [Move.BlastBurn]: {
    accuracy: 90,
    basePower: 150,
    category: MoveCategory.Special,
    name: "Blast Burn",
    pp: 5,
    priority: 0,
    type: Type.Fire,
    description: "User cannot move next turn.",
  },
  [Move.BlazeKick]: {
    accuracy: 90,
    basePower: 85,
    category: MoveCategory.Physical,
    name: "Blaze Kick",
    pp: 10,
    priority: 0,
    type: Type.Fire,
    description: "Has a 10% chance to burn the target.",
  },
  [Move.Block]: {
    accuracy: null,
    basePower: null,
    category: MoveCategory.Status,
    name: "Block",
    pp: 5,
    priority: 0,
    type: Type.Normal,
    description: "Prevents the target from switching out.",
  },
  [Move.Blizzard]: {
    accuracy: 70,
    basePower: 110,
    category: MoveCategory.Special,
    name: "Blizzard",
    pp: 5,
    priority: 0,
    type: Type.Ice,
    description: "Has a 10% chance to freeze the target.",
  },
  [Move.BodySlam]: {
    accuracy: 100,
    basePower: 85,
    category: MoveCategory.Physical,
    name: "Body Slam",
    pp: 15,
    priority: 0,
    type: Type.Normal,
    description: "Has a 30% chance to paralyze the target.",
  },
  [Move.BoneClub]: {
    accuracy: 85,
    basePower: 65,
    category: MoveCategory.Physical,
    name: "Bone Club",
    pp: 20,
    priority: 0,
    type: Type.Ground,
    description: "Has a 10% chance to make the target flinch.",
  },
  [Move.Bonemerang]: {
    accuracy: 90,
    basePower: 50,
    category: MoveCategory.Physical,
    name: "Bonemerang",
    pp: 10,
    priority: 0,
    type: Type.Ground,
    description: "Hits twice in one turn.",
  },
  [Move.Bounce]: {
    accuracy: 85,
    basePower: 85,
    category: MoveCategory.Physical,
    name: "Bounce",
    pp: 5,
    priority: 0,
    type: Type.Flying,
    description:
      "User bounces high into the air, dodging all attacks, and hits on the second turn.",
  },
  [Move.BrickBreak]: {
    accuracy: 100,
    basePower: 75,
    category: MoveCategory.Physical,
    name: "Brick Break",
    pp: 15,
    priority: 0,
    type: Type.Fighting,
    description: "Breaks through Reflect and Light Screen barriers.",
  },
  [Move.Bubble]: {
    accuracy: 100,
    basePower: 40,
    category: MoveCategory.Special,
    name: "Bubble",
    pp: 30,
    priority: 0,
    type: Type.Water,
    description: "Has a 10% chance to lower the target's Speed by one stage.",
  },
  [Move.BubbleBeam]: {
    accuracy: 100,
    basePower: 65,
    category: MoveCategory.Special,
    name: "Bubble Beam",
    pp: 20,
    priority: 0,
    type: Type.Water,
    description: "Has a 10% chance to lower the target's Speed by one stage.",
  },
  [Move.BulkUp]: {
    accuracy: null,
    basePower: null,
    category: MoveCategory.Status,
    name: "Bulk Up",
    pp: 20,
    priority: 0,
    type: Type.Fighting,
    description: "Raises the user's Attack and Defense by one stage.",
  },
  [Move.BulletSeed]: {
    accuracy: 100,
    basePower: 25,
    category: MoveCategory.Physical,
    name: "Bullet Seed",
    pp: 30,
    priority: 0,
    type: Type.Grass,
    description: "Hits 2-5 times in one turn.",
  },
  [Move.CalmMind]: {
    accuracy: null,
    basePower: null,
    category: MoveCategory.Status,
    name: "Calm Mind",
    pp: 20,
    priority: 0,
    type: Type.Psychic,
    description:
      "Raises the user's Special Attack and Special Defense by one stage.",
  },
  [Move.Camouflage]: {
    accuracy: null,
    basePower: null,
    category: MoveCategory.Status,
    name: "Camouflage",
    pp: 20,
    priority: 0,
    type: Type.Normal,
    description: "Changes the user's type to match the terrain.",
  },
  [Move.Charge]: {
    accuracy: null,
    basePower: null,
    category: MoveCategory.Status,
    name: "Charge",
    pp: 20,
    priority: 0,
    type: Type.Electric,
    description:
      "Raises the user's Special Defense by one stage. Raises the power of the user's next Electric-type move by 2.",
  },
  [Move.Clamp]: {
    accuracy: 85,
    basePower: 35,
    category: MoveCategory.Physical,
    name: "Clamp",
    pp: 15,
    priority: 0,
    type: Type.Water,
    description: "Traps the target for 4-5 turns.",
  },
  [Move.ConfuseRay]: {
    accuracy: 100,
    basePower: null,
    category: MoveCategory.Status,
    name: "Confuse Ray",
    pp: 10,
    priority: 0,
    type: Type.Ghost,
    description: "Confuses the target.",
  },
  [Move.Confusion]: {
    accuracy: 100,
    basePower: 50,
    category: MoveCategory.Special,
    name: "Confusion",
    pp: 25,
    priority: 0,
    type: Type.Psychic,
    description: "Has a 10% chance to confuse the target.",
  },
  [Move.Constrict]: {
    accuracy: 100,
    basePower: 10,
    category: MoveCategory.Physical,
    name: "Constrict",
    pp: 35,
    priority: 0,
    type: Type.Normal,
    description: "Has a 10% chance to lower the target's Speed by one stage.",
  },
  [Move.Conversion]: {
    accuracy: null,
    basePower: null,
    category: MoveCategory.Status,
    name: "Conversion",
    pp: 30,
    priority: 0,
    type: Type.Normal,
    description: "Changes the user's type to match a random move it knows.",
  },
  [Move.Counter]: {
    accuracy: 100,
    basePower: null,
    category: MoveCategory.Physical,
    name: "Counter",
    pp: 20,
    priority: -5,
    type: Type.Fighting,
    description: "If hit by physical attack, returns double damage.",
  },
  [Move.CometPunch]: {
    accuracy: 85,
    basePower: 18,
    category: MoveCategory.Physical,
    name: "Comet Punch",
    pp: 15,
    priority: 0,
    type: Type.Normal,
    description: "Hits 2-5 times in one turn.",
  },
  [Move.CosmicPower]: {
    accuracy: null,
    basePower: null,
    category: MoveCategory.Status,
    name: "Cosmic Power",
    pp: 20,
    priority: 0,
    type: Type.Psychic,
    description: "Raises the user's Defense and Special Defense by one stage.",
  },
  [Move.Covet]: {
    accuracy: 100,
    basePower: 40,
    category: MoveCategory.Physical,
    name: "Covet",
    pp: 40,
    priority: 0,
    type: Type.Normal,
    description:
      "If the user is not holding an item, it steals the target's item.",
  },
  [Move.Crabhammer]: {
    accuracy: 90,
    basePower: 100,
    category: MoveCategory.Physical,
    name: "Crabhammer",
    pp: 10,
    priority: 0,
    type: Type.Water,
    description: "High critical hit ratio.",
  },
  [Move.CrushClaw]: {
    accuracy: 95,
    basePower: 75,
    category: MoveCategory.Physical,
    name: "Crush Claw",
    pp: 10,
    priority: 0,
    type: Type.Normal,
    description: "Has a 50% chance to lower the target's Defense by one stage.",
  },
  [Move.Cut]: {
    accuracy: 95,
    basePower: 50,
    category: MoveCategory.Physical,
    name: "Cut",
    pp: 30,
    priority: 0,
    type: Type.Normal,
    description: "No additional effect.",
  },
  [Move.DefenseCurl]: {
    accuracy: null,
    basePower: null,
    category: MoveCategory.Status,
    name: "Defense Curl",
    pp: 40,
    priority: 0,
    type: Type.Normal,
    description: "Raises the user's Defense by one stage.",
  },
  [Move.Dig]: {
    accuracy: 100,
    basePower: 80,
    category: MoveCategory.Physical,
    name: "Dig",
    pp: 10,
    priority: 0,
    type: Type.Ground,
    description:
      "Digs underground on first turn, attacks on second. Can also escape from caves.",
  },
  [Move.Disable]: {
    accuracy: 100,
    basePower: null,
    category: MoveCategory.Status,
    name: "Disable",
    pp: 20,
    priority: 0,
    type: Type.Normal,
    description: "Disables the target's last used move for 1-8 turns.",
  },
  [Move.Dive]: {
    accuracy: 100,
    basePower: 60,
    category: MoveCategory.Physical,
    name: "Dive",
    pp: 10,
    priority: 0,
    type: Type.Water,
    description:
      "Dives underwater on the first turn, then hits on the second turn.",
  },
  [Move.DizzyPunch]: {
    accuracy: 100,
    basePower: 70,
    category: MoveCategory.Physical,
    name: "Dizzy Punch",
    pp: 10,
    priority: 0,
    type: Type.Normal,
    description: "Has a 20% chance to confuse the target.",
  },
  [Move.DoomDesire]: {
    accuracy: 85,
    basePower: 140,
    category: MoveCategory.Special,
    name: "Doom Desire",
    pp: 5,
    priority: 0,
    type: Type.Steel,
    description: "Hits two turns after being used.",
  },
  [Move.DragonClaw]: {
    accuracy: 100,
    basePower: 80,
    category: MoveCategory.Physical,
    name: "Dragon Claw",
    pp: 15,
    priority: 0,
    type: Type.Dragon,
    description: "No additional effect.",
  },
  [Move.DragonDance]: {
    accuracy: null,
    basePower: null,
    category: MoveCategory.Status,
    name: "Dragon Dance",
    pp: 20,
    priority: 0,
    type: Type.Dragon,
    description: "Raises the user's Attack and Speed by one stage.",
  },
  [Move.DoubleKick]: {
    accuracy: 100,
    basePower: 30,
    category: MoveCategory.Physical,
    name: "Double Kick",
    pp: 30,
    priority: 0,
    type: Type.Fighting,
    description: "Hits twice in one turn.",
  },
  [Move.DoubleSlap]: {
    accuracy: 85,
    basePower: 15,
    category: MoveCategory.Physical,
    name: "Double Slap",
    pp: 10,
    priority: 0,
    type: Type.Normal,
    description: "Hits 2-5 times in one turn.",
  },
  [Move.DoubleTeam]: {
    accuracy: null,
    basePower: null,
    category: MoveCategory.Status,
    name: "Double Team",
    pp: 15,
    priority: 0,
    type: Type.Normal,
    description: "Raises the user's evasion by one stage.",
  },
  [Move.DoubleEdge]: {
    accuracy: 100,
    basePower: 120,
    category: MoveCategory.Physical,
    name: "Double-Edge",
    pp: 15,
    priority: 0,
    type: Type.Normal,
    description: "User receives recoil damage.",
  },
  [Move.DragonRage]: {
    accuracy: 100,
    basePower: null,
    category: MoveCategory.Special,
    name: "Dragon Rage",
    pp: 10,
    priority: 0,
    type: Type.Dragon,
    description: "Always inflicts 40 HP.",
  },
  [Move.DreamEater]: {
    accuracy: 100,
    basePower: 100,
    category: MoveCategory.Special,
    name: "Dream Eater",
    pp: 15,
    priority: 0,
    type: Type.Psychic,
    description: "User recovers half the HP inflicted on a sleeping target.",
  },
  [Move.DrillPeck]: {
    accuracy: 100,
    basePower: 80,
    category: MoveCategory.Physical,
    name: "Drill Peck",
    pp: 20,
    priority: 0,
    type: Type.Flying,
    description: "No additional effect.",
  },
  [Move.Earthquake]: {
    accuracy: 100,
    basePower: 100,
    category: MoveCategory.Physical,
    name: "Earthquake",
    pp: 10,
    priority: 0,
    type: Type.Ground,
    description: "Hits adjacent Pokemon.",
  },
  [Move.EggBomb]: {
    accuracy: 75,
    basePower: 100,
    category: MoveCategory.Physical,
    name: "Egg Bomb",
    pp: 10,
    priority: 0,
    type: Type.Normal,
    description: "No additional effect.",
  },
  [Move.Endeavor]: {
    accuracy: 100,
    basePower: null,
    category: MoveCategory.Physical,
    name: "Endeavor",
    pp: 5,
    priority: 0,
    type: Type.Normal,
    description: "Lowers the target's HP to equal the user's HP.",
  },
  [Move.Ember]: {
    accuracy: 100,
    basePower: 40,
    category: MoveCategory.Special,
    name: "Ember",
    pp: 25,
    priority: 0,
    type: Type.Fire,
    description: "Has a 10% chance to burn the target.",
  },
  [Move.Eruption]: {
    accuracy: 100,
    basePower: null,
    category: MoveCategory.Special,
    name: "Eruption",
    pp: 5,
    priority: 0,
    type: Type.Fire,
    description: "The lower the user's HP, the lower the move's power.",
  },
  [Move.Explosion]: {
    accuracy: 100,
    basePower: 250,
    category: MoveCategory.Physical,
    name: "Explosion",
    pp: 5,
    priority: 0,
    type: Type.Normal,
    description: "User faints.",
  },
  [Move.Facade]: {
    accuracy: 100,
    basePower: 70,
    category: MoveCategory.Physical,
    name: "Facade",
    pp: 20,
    priority: 0,
    type: Type.Normal,
    description: "Power doubles if the user is burned, poisoned, or paralyzed.",
  },
  [Move.FakeOut]: {
    accuracy: 100,
    basePower: 40,
    category: MoveCategory.Physical,
    name: "Fake Out",
    pp: 10,
    priority: 3,
    type: Type.Normal,
    description: "Hits first. First turn out only. 100% flinch chance.",
  },
  [Move.FakeTears]: {
    accuracy: 100,
    basePower: null,
    category: MoveCategory.Status,
    name: "Fake Tears",
    pp: 20,
    priority: 0,
    type: Type.Dark,
    description: "Lowers the target's Special Defense by two stages.",
  },
  [Move.FeatherDance]: {
    accuracy: 100,
    basePower: null,
    category: MoveCategory.Status,
    name: "Feather Dance",
    pp: 15,
    priority: 0,
    type: Type.Flying,
    description: "Lowers the target's Attack by two stages.",
  },
  [Move.FireBlast]: {
    accuracy: 85,
    basePower: 110,
    category: MoveCategory.Special,
    name: "Fire Blast",
    pp: 5,
    priority: 0,
    type: Type.Fire,
    description: "Has a 10% chance to burn the target.",
  },
  [Move.FirePunch]: {
    accuracy: 100,
    basePower: 75,
    category: MoveCategory.Physical,
    name: "Fire Punch",
    pp: 15,
    priority: 0,
    type: Type.Fire,
    description: "Has a 10% chance to burn the target.",
  },
  [Move.FireSpin]: {
    accuracy: 85,
    basePower: 35,
    category: MoveCategory.Special,
    name: "Fire Spin",
    pp: 15,
    priority: 0,
    type: Type.Fire,
    description: "Traps the target for 4-5 turns.",
  },
  [Move.Flatter]: {
    accuracy: 100,
    basePower: null,
    category: MoveCategory.Status,
    name: "Flatter",
    pp: 15,
    priority: 0,
    type: Type.Dark,
    description:
      "Raises the target's Special Attack by one stage and confuses it.",
  },
  [Move.Flamethrower]: {
    accuracy: 100,
    basePower: 90,
    category: MoveCategory.Special,
    name: "Flamethrower",
    pp: 15,
    priority: 0,
    type: Type.Fire,
    description: "Has a 10% chance to burn the target.",
  },
  [Move.Flash]: {
    accuracy: 100,
    basePower: null,
    category: MoveCategory.Status,
    name: "Flash",
    pp: 20,
    priority: 0,
    type: Type.Normal,
    description: "Lowers the target's accuracy by one stage.",
  },
  [Move.Fly]: {
    accuracy: 95,
    basePower: 90,
    category: MoveCategory.Physical,
    name: "Fly",
    pp: 15,
    priority: 0,
    type: Type.Flying,
    description:
      "Flies up on first turn, then strikes the next turn. Can also be used to fly to any familiar town.",
  },
  [Move.FocusEnergy]: {
    accuracy: null,
    basePower: null,
    category: MoveCategory.Status,
    name: "Focus Energy",
    pp: 30,
    priority: 0,
    type: Type.Normal,
    description: "Increases the user's chance to score a critical hit.",
  },
  [Move.FocusPunch]: {
    accuracy: 100,
    basePower: 150,
    category: MoveCategory.Physical,
    name: "Focus Punch",
    pp: 20,
    priority: -3,
    type: Type.Fighting,
    description:
      "If the user takes damage before attacking, the attack is canceled.",
  },
  [Move.FollowMe]: {
    accuracy: null,
    basePower: null,
    category: MoveCategory.Status,
    name: "Follow Me",
    pp: 20,
    priority: 2,
    type: Type.Normal,
    description:
      "The target's attention is drawn to the user. All opponents' attacks are aimed toward the user.",
  },
  [Move.FrenzyPlant]: {
    accuracy: 90,
    basePower: 150,
    category: MoveCategory.Special,
    name: "Frenzy Plant",
    pp: 5,
    priority: 0,
    type: Type.Grass,
    description: "User cannot move next turn.",
  },
  [Move.FuryAttack]: {
    accuracy: 85,
    basePower: 15,
    category: MoveCategory.Physical,
    name: "Fury Attack",
    pp: 20,
    priority: 0,
    type: Type.Normal,
    description: "Hits 2-5 times in one turn.",
  },
  [Move.FurySwipes]: {
    accuracy: 80,
    basePower: 18,
    category: MoveCategory.Physical,
    name: "Fury Swipes",
    pp: 15,
    priority: 0,
    type: Type.Normal,
    description: "Hits 2-5 times in one turn.",
  },
  [Move.Glare]: {
    accuracy: 100,
    basePower: null,
    category: MoveCategory.Status,
    name: "Glare",
    pp: 30,
    priority: 0,
    type: Type.Normal,
    description: "Paralyzes the target.",
  },
  [Move.GrassWhistle]: {
    accuracy: 55,
    basePower: null,
    category: MoveCategory.Status,
    name: "Grass Whistle",
    pp: 15,
    priority: 0,
    type: Type.Grass,
    description: "Puts the target to sleep.",
  },
  [Move.Growl]: {
    accuracy: 100,
    basePower: null,
    category: MoveCategory.Status,
    name: "Growl",
    pp: 40,
    priority: 0,
    type: Type.Normal,
    description: "Lowers the target's Attack by one stage.",
  },
  [Move.Growth]: {
    accuracy: null,
    basePower: null,
    category: MoveCategory.Status,
    name: "Growth",
    pp: 20,
    priority: 0,
    type: Type.Normal,
    description: "Raises the user's Attack and Special Attack by one stage.",
  },
  [Move.Grudge]: {
    accuracy: null,
    basePower: null,
    category: MoveCategory.Status,
    name: "Grudge",
    pp: 5,
    priority: 0,
    type: Type.Ghost,
    description:
      "If the user faints this turn, the target loses all PP for this move.",
  },
  [Move.Guillotine]: {
    accuracy: 30,
    basePower: null,
    category: MoveCategory.Physical,
    name: "Guillotine",
    pp: 5,
    priority: 0,
    type: Type.Normal,
    description: "OHKOs the target.",
  },
  [Move.Gust]: {
    accuracy: 100,
    basePower: 40,
    category: MoveCategory.Special,
    name: "Gust",
    pp: 35,
    priority: 0,
    type: Type.Flying,
    description: "No additional effect.",
  },
  [Move.Harden]: {
    accuracy: null,
    basePower: null,
    category: MoveCategory.Status,
    name: "Harden",
    pp: 30,
    priority: 0,
    type: Type.Normal,
    description: "Raises the user's Defense by one stage.",
  },
  [Move.Hail]: {
    accuracy: null,
    basePower: null,
    category: MoveCategory.Status,
    name: "Hail",
    pp: 10,
    priority: 0,
    type: Type.Ice,
    description: "Non-Ice types are damaged for 1/16 their max HP per turn.",
  },
  [Move.Haze]: {
    accuracy: null,
    basePower: null,
    category: MoveCategory.Status,
    name: "Haze",
    pp: 30,
    priority: 0,
    type: Type.Ice,
    description: "Resets all stat changes.",
  },
  [Move.Headbutt]: {
    accuracy: 100,
    basePower: 70,
    category: MoveCategory.Physical,
    name: "Headbutt",
    pp: 15,
    priority: 0,
    type: Type.Normal,
    description: "Has a 30% chance to make the target flinch.",
  },
  [Move.HeatWave]: {
    accuracy: 90,
    basePower: 100,
    category: MoveCategory.Special,
    name: "Heat Wave",
    pp: 10,
    priority: 0,
    type: Type.Fire,
    description: "Has a 10% chance to burn the target.",
  },
  [Move.HelpingHand]: {
    accuracy: null,
    basePower: null,
    category: MoveCategory.Status,
    name: "Helping Hand",
    pp: 20,
    priority: 5,
    type: Type.Normal,
    description: "Raises the power of the target's move by 1.5x.",
  },
  [Move.Howl]: {
    accuracy: null,
    basePower: null,
    category: MoveCategory.Status,
    name: "Howl",
    pp: 40,
    priority: 0,
    type: Type.Normal,
    description: "Raises the user's Attack by one stage.",
  },
  [Move.HighJumpKick]: {
    accuracy: 90,
    basePower: 130,
    category: MoveCategory.Physical,
    name: "High Jump Kick",
    pp: 10,
    priority: 0,
    type: Type.Fighting,
    description:
      "If this attack misses, the user takes half the damage it would have inflicted in recoil.",
  },
  [Move.HornAttack]: {
    accuracy: 100,
    basePower: 65,
    category: MoveCategory.Physical,
    name: "Horn Attack",
    pp: 25,
    priority: 0,
    type: Type.Normal,
    description: "No additional effect.",
  },
  [Move.HornDrill]: {
    accuracy: 30,
    basePower: null,
    category: MoveCategory.Physical,
    name: "Horn Drill",
    pp: 5,
    priority: 0,
    type: Type.Normal,
    description: "OHKOs the target.",
  },
  [Move.HydroCannon]: {
    accuracy: 90,
    basePower: 150,
    category: MoveCategory.Special,
    name: "Hydro Cannon",
    pp: 5,
    priority: 0,
    type: Type.Water,
    description: "User cannot move next turn.",
  },
  [Move.HydroPump]: {
    accuracy: 80,
    basePower: 110,
    category: MoveCategory.Special,
    name: "Hydro Pump",
    pp: 5,
    priority: 0,
    type: Type.Water,
    description: "No additional effect.",
  },
  [Move.HyperBeam]: {
    accuracy: 90,
    basePower: 150,
    category: MoveCategory.Special,
    name: "Hyper Beam",
    pp: 5,
    priority: 0,
    type: Type.Normal,
    description: "User cannot move next turn.",
  },
  [Move.HyperFang]: {
    accuracy: 90,
    basePower: 80,
    category: MoveCategory.Physical,
    name: "Hyper Fang",
    pp: 15,
    priority: 0,
    type: Type.Normal,
    description: "Has a 10% chance to make the target flinch.",
  },
  [Move.HyperVoice]: {
    accuracy: 100,
    basePower: 90,
    category: MoveCategory.Special,
    name: "Hyper Voice",
    pp: 10,
    priority: 0,
    type: Type.Normal,
    description: "No additional effect.",
  },
  [Move.Hypnosis]: {
    accuracy: 60,
    basePower: null,
    category: MoveCategory.Status,
    name: "Hypnosis",
    pp: 20,
    priority: 0,
    type: Type.Psychic,
    description: "Puts the target to sleep.",
  },
  [Move.IceBall]: {
    accuracy: 90,
    basePower: 30,
    category: MoveCategory.Physical,
    name: "Ice Ball",
    pp: 20,
    priority: 0,
    type: Type.Ice,
    description:
      "Hits 2-5 times in one turn. Power doubles with each successive hit.",
  },
  [Move.IceBeam]: {
    accuracy: 100,
    basePower: 90,
    category: MoveCategory.Special,
    name: "Ice Beam",
    pp: 10,
    priority: 0,
    type: Type.Ice,
    description: "Has a 10% chance to freeze the target.",
  },
  [Move.IcePunch]: {
    accuracy: 100,
    basePower: 75,
    category: MoveCategory.Physical,
    name: "Ice Punch",
    pp: 15,
    priority: 0,
    type: Type.Ice,
    description: "Has a 10% chance to freeze the target.",
  },
  [Move.IcicleSpear]: {
    accuracy: 100,
    basePower: 25,
    category: MoveCategory.Physical,
    name: "Icicle Spear",
    pp: 30,
    priority: 0,
    type: Type.Ice,
    description: "Hits 2-5 times in one turn.",
  },
  [Move.Imprison]: {
    accuracy: null,
    basePower: null,
    category: MoveCategory.Status,
    name: "Imprison",
    pp: 10,
    priority: 0,
    type: Type.Psychic,
    description:
      "Prevents the target from using any moves that the user also knows.",
  },
  [Move.Ingrain]: {
    accuracy: null,
    basePower: null,
    category: MoveCategory.Status,
    name: "Ingrain",
    pp: 20,
    priority: 0,
    type: Type.Grass,
    description: "The user restores 1/16 of its max HP each turn.",
  },
  [Move.IronDefense]: {
    accuracy: null,
    basePower: null,
    category: MoveCategory.Status,
    name: "Iron Defense",
    pp: 15,
    priority: 0,
    type: Type.Steel,
    description: "Raises the user's Defense by two stages.",
  },
  [Move.JumpKick]: {
    accuracy: 95,
    basePower: 100,
    category: MoveCategory.Physical,
    name: "Jump Kick",
    pp: 10,
    priority: 0,
    type: Type.Fighting,
    description:
      "If this attack misses, the user takes half the damage it would have inflicted in recoil.",
  },
  [Move.KarateChop]: {
    accuracy: 100,
    basePower: 50,
    category: MoveCategory.Physical,
    name: "Karate Chop",
    pp: 25,
    priority: 0,
    type: Type.Fighting,
    description: "High critical hit ratio.",
  },
  [Move.Kinesis]: {
    accuracy: 80,
    basePower: null,
    category: MoveCategory.Status,
    name: "Kinesis",
    pp: 15,
    priority: 0,
    type: Type.Psychic,
    description: "Lowers the target's accuracy by one stage.",
  },
  [Move.KnockOff]: {
    accuracy: 100,
    basePower: 20,
    category: MoveCategory.Physical,
    name: "Knock Off",
    pp: 20,
    priority: 0,
    type: Type.Dark,
    description:
      "Removes the target's held item. Power doubles if the target is holding an item.",
  },
  [Move.LeafBlade]: {
    accuracy: 100,
    basePower: 70,
    category: MoveCategory.Physical,
    name: "Leaf Blade",
    pp: 15,
    priority: 0,
    type: Type.Grass,
    description: "High critical hit ratio.",
  },
  [Move.LeechLife]: {
    accuracy: 100,
    basePower: 20,
    category: MoveCategory.Physical,
    name: "Leech Life",
    pp: 15,
    priority: 0,
    type: Type.Bug,
    description: "User recovers 50% of the damage dealt.",
  },
  [Move.LeechSeed]: {
    accuracy: 90,
    basePower: null,
    category: MoveCategory.Status,
    name: "Leech Seed",
    pp: 10,
    priority: 0,
    type: Type.Grass,
    description: "User steals 1/8 of the target's max HP each turn.",
  },
  [Move.Leer]: {
    accuracy: 100,
    basePower: null,
    category: MoveCategory.Status,
    name: "Leer",
    pp: 30,
    priority: 0,
    type: Type.Normal,
    description: "Lowers the target's Defense by one stage.",
  },
  [Move.Lick]: {
    accuracy: 100,
    basePower: 30,
    category: MoveCategory.Physical,
    name: "Lick",
    pp: 30,
    priority: 0,
    type: Type.Ghost,
    description: "Has a 30% chance to paralyze the target.",
  },
  [Move.LightScreen]: {
    accuracy: null,
    basePower: null,
    category: MoveCategory.Status,
    name: "Light Screen",
    pp: 30,
    priority: 0,
    type: Type.Psychic,
    description: "Halves damage from Special attacks for 5 turns.",
  },
  [Move.LovelyKiss]: {
    accuracy: 75,
    basePower: null,
    category: MoveCategory.Status,
    name: "Lovely Kiss",
    pp: 10,
    priority: 0,
    type: Type.Normal,
    description: "Puts the target to sleep.",
  },
  [Move.LowKick]: {
    accuracy: 100,
    basePower: null,
    category: MoveCategory.Physical,
    name: "Low Kick",
    pp: 20,
    priority: 0,
    type: Type.Fighting,
    description: "The heavier the target, the greater the damage.",
  },
  [Move.LusterPurge]: {
    accuracy: 100,
    basePower: 70,
    category: MoveCategory.Special,
    name: "Luster Purge",
    pp: 5,
    priority: 0,
    type: Type.Psychic,
    description:
      "Has a 50% chance to lower the target's Special Defense by one stage.",
  },
  [Move.MagicCoat]: {
    accuracy: null,
    basePower: null,
    category: MoveCategory.Status,
    name: "Magic Coat",
    pp: 15,
    priority: 4,
    type: Type.Psychic,
    description: "Reflects most non-damaging moves back at their user.",
  },
  [Move.MagicalLeaf]: {
    accuracy: null,
    basePower: 60,
    category: MoveCategory.Special,
    name: "Magical leaf",
    pp: 20,
    priority: 0,
    type: Type.Grass,
    description: "Ignores accuracy and evasion modifiers.",
  },
  [Move.Meditate]: {
    accuracy: null,
    basePower: null,
    category: MoveCategory.Status,
    name: "Meditate",
    pp: 40,
    priority: 0,
    type: Type.Psychic,
    description: "Raises the user's Attack by one stage.",
  },
  [Move.MegaDrain]: {
    accuracy: 100,
    basePower: 40,
    category: MoveCategory.Special,
    name: "Mega Drain",
    pp: 15,
    priority: 0,
    type: Type.Grass,
    description: "User recovers 50% of the damage dealt.",
  },
  [Move.MegaKick]: {
    accuracy: 75,
    basePower: 120,
    category: MoveCategory.Physical,
    name: "Mega Kick",
    pp: 5,
    priority: 0,
    type: Type.Normal,
    description: "No additional effect.",
  },
  [Move.MegaPunch]: {
    accuracy: 85,
    basePower: 80,
    category: MoveCategory.Physical,
    name: "Mega Punch",
    pp: 20,
    priority: 0,
    type: Type.Normal,
    description: "No additional effect.",
  },
  [Move.Memento]: {
    accuracy: 100,
    basePower: null,
    category: MoveCategory.Status,
    name: "Memento",
    pp: 10,
    priority: 0,
    type: Type.Dark,
    description:
      "Lowers the target's Attack and Special Attack by two stages. User faints.",
  },
  [Move.MetalSound]: {
    accuracy: 85,
    basePower: null,
    category: MoveCategory.Status,
    name: "Metal sound",
    pp: 40,
    priority: 0,
    type: Type.Steel,
    description: "Lowers the target's Special Defense by two stages.",
  },
  [Move.MeteorMash]: {
    accuracy: 90,
    basePower: 100,
    category: MoveCategory.Physical,
    name: "Meteor Mash",
    pp: 10,
    priority: 0,
    type: Type.Steel,
    description: "Has a 20% chance to raise the user's Attack by one stage.",
  },
  [Move.Metronome]: {
    accuracy: null,
    basePower: null,
    category: MoveCategory.Status,
    name: "Metronome",
    pp: 10,
    priority: 0,
    type: Type.Normal,
    description: "Picks a random move.",
  },
  [Move.Mimic]: {
    accuracy: null,
    basePower: null,
    category: MoveCategory.Status,
    name: "Mimic",
    pp: 10,
    priority: 0,
    type: Type.Normal,
    description: "Copies the target's last used move.",
  },
  [Move.Minimize]: {
    accuracy: null,
    basePower: null,
    category: MoveCategory.Status,
    name: "Minimize",
    pp: 20,
    priority: 0,
    type: Type.Normal,
    description: "Raises the user's evasion by one stage.",
  },
  [Move.MirrorMove]: {
    accuracy: null,
    basePower: null,
    category: MoveCategory.Status,
    name: "Mirror Move",
    pp: 20,
    priority: 0,
    type: Type.Flying,
    description: "Uses the target's last used move against it.",
  },
  [Move.Mist]: {
    accuracy: null,
    basePower: null,
    category: MoveCategory.Status,
    name: "Mist",
    pp: 30,
    priority: 0,
    type: Type.Ice,
    description: "Protects the user's stats from being changed by enemy moves.",
  },
  [Move.MistBall]: {
    accuracy: 100,
    basePower: 70,
    category: MoveCategory.Special,
    name: "Mist Ball",
    pp: 5,
    priority: 0,
    type: Type.Psychic,
    description:
      "Has a 50% chance to lower the target's Special Attack by one stage.",
  },
  [Move.MudShot]: {
    accuracy: 95,
    basePower: 55,
    category: MoveCategory.Special,
    name: "Mud Shot",
    pp: 15,
    priority: 0,
    type: Type.Ground,
    description: "Has a 100% chance to lower the target's Speed by one stage.",
  },
  [Move.MudSport]: {
    accuracy: null,
    basePower: null,
    category: MoveCategory.Status,
    name: "Mud Sport",
    pp: 15,
    priority: 0,
    type: Type.Ground,
    description:
      "Weakens Electric-type attacks to 1/3 their power during this turn.",
  },
  [Move.MuddyWater]: {
    accuracy: 85,
    basePower: 95,
    category: MoveCategory.Special,
    name: "Muddy Water",
    pp: 10,
    priority: 0,
    type: Type.Water,
    description:
      "Has a 30% chance to lower the target's Accuracy by one stage.",
  },
  [Move.NaturePower]: {
    accuracy: null,
    basePower: null,
    category: MoveCategory.Status,
    name: "Nature Power",
    pp: 20,
    priority: 0,
    type: Type.Normal,
    description: "Uses a certain move based on the current terrain.",
  },
  [Move.NeedleArm]: {
    accuracy: 100,
    basePower: 60,
    category: MoveCategory.Physical,
    name: "Needle Arm",
    pp: 15,
    priority: 0,
    type: Type.Grass,
    description: "Has a 30% chance to make the target flinch.",
  },
  [Move.NightShade]: {
    accuracy: 100,
    basePower: null,
    category: MoveCategory.Special,
    name: "Night Shade",
    pp: 15,
    priority: 0,
    type: Type.Ghost,
    description: "Inflicts damage equal to the user's level.",
  },
  [Move.OdorSleuth]: {
    accuracy: null,
    basePower: null,
    category: MoveCategory.Status,
    name: "Odor Sleuth",
    pp: 40,
    priority: 0,
    type: Type.Normal,
    description:
      "Resets the target's Evasion to normal and removes Ghost's immunity to Normal and Fighting.",
  },
  [Move.Overheat]: {
    accuracy: 90,
    basePower: 140,
    category: MoveCategory.Special,
    name: "Overheat",
    pp: 5,
    priority: 0,
    type: Type.Fire,
    description:
      "Lowers the user's Special Attack by two stages after inflicting damage.",
  },
  [Move.PayDay]: {
    accuracy: 100,
    basePower: 40,
    category: MoveCategory.Physical,
    name: "Pay Day",
    pp: 20,
    priority: 0,
    type: Type.Normal,
    description: "Worth double the money if used in a Trainer battle.",
  },
  [Move.Peck]: {
    accuracy: 100,
    basePower: 35,
    category: MoveCategory.Physical,
    name: "Peck",
    pp: 35,
    priority: 0,
    type: Type.Flying,
    description: "No additional effect.",
  },
  [Move.PetalDance]: {
    accuracy: 100,
    basePower: 120,
    category: MoveCategory.Special,
    name: "Petal Dance",
    pp: 10,
    priority: 0,
    type: Type.Grass,
    description: "User cannot move next turn.",
  },
  [Move.PinMissile]: {
    accuracy: 95,
    basePower: 25,
    category: MoveCategory.Physical,
    name: "Pin Missile",
    pp: 20,
    priority: 0,
    type: Type.Bug,
    description: "Hits 2-5 times in one turn.",
  },
  [Move.PoisonFang]: {
    accuracy: 100,
    basePower: 50,
    category: MoveCategory.Physical,
    name: "Poison Fang",
    pp: 15,
    priority: 0,
    type: Type.Poison,
    description: "Has a 50% chance to badly poison the target.",
  },
  [Move.PoisonGas]: {
    accuracy: 90,
    basePower: null,
    category: MoveCategory.Status,
    name: "Poison Gas",
    pp: 40,
    priority: 0,
    type: Type.Poison,
    description: "Poisons the target.",
  },
  [Move.PoisonPowder]: {
    accuracy: 75,
    basePower: null,
    category: MoveCategory.Status,
    name: "Poison Powder",
    pp: 35,
    priority: 0,
    type: Type.Poison,
    description: "Poisons the target.",
  },
  [Move.PoisonSting]: {
    accuracy: 100,
    basePower: 15,
    category: MoveCategory.Physical,
    name: "Poison Sting",
    pp: 35,
    priority: 0,
    type: Type.Poison,
    description: "Has a 30% chance to poison the target.",
  },
  [Move.PoisonTail]: {
    accuracy: 100,
    basePower: 50,
    category: MoveCategory.Physical,
    name: "Poison Tail",
    pp: 25,
    priority: 0,
    type: Type.Poison,
    description: "Has a 10% chance to poison the target.",
  },
  [Move.Pound]: {
    accuracy: 100,
    basePower: 40,
    category: MoveCategory.Physical,
    name: "Pound",
    pp: 35,
    priority: 0,
    type: Type.Normal,
    description: "No additional effect.",
  },
  [Move.Psybeam]: {
    accuracy: 100,
    basePower: 65,
    category: MoveCategory.Special,
    name: "Psybeam",
    pp: 20,
    priority: 0,
    type: Type.Psychic,
    description: "Has a 10% chance to confuse the target.",
  },
  [Move.PsychoBoost]: {
    accuracy: 90,
    basePower: 140,
    category: MoveCategory.Special,
    name: "Psycho Boost",
    pp: 5,
    priority: 0,
    type: Type.Psychic,
    description:
      "Lowers the user's Special Attack by two stages after inflicting damage.",
  },
  [Move.Psychic]: {
    accuracy: 100,
    basePower: 90,
    category: MoveCategory.Special,
    name: Type.Psychic,
    pp: 10,
    priority: 0,
    type: Type.Psychic,
    description:
      "Has a 10% chance to lower the target's Special Defense by one stage.",
  },
  [Move.Psywave]: {
    accuracy: 100,
    basePower: null,
    category: MoveCategory.Special,
    name: "Psywave",
    pp: 15,
    priority: 0,
    type: Type.Psychic,
    description: "Inflicts damage 50-150% of the user's level.",
  },
  [Move.QuickAttack]: {
    accuracy: 100,
    basePower: 40,
    category: MoveCategory.Physical,
    name: "Quick Attack",
    pp: 30,
    priority: 1,
    type: Type.Normal,
    description: "Usually goes first.",
  },
  [Move.Rage]: {
    accuracy: 100,
    basePower: 20,
    category: MoveCategory.Physical,
    name: "Rage",
    pp: 20,
    priority: 0,
    type: Type.Normal,
    description: "Raises the user's Attack by one stage if hit during use.",
  },
  [Move.RazorLeaf]: {
    accuracy: 95,
    basePower: 55,
    category: MoveCategory.Physical,
    name: "Razor Leaf",
    pp: 25,
    priority: 0,
    type: Type.Grass,
    description: "High critical hit ratio.",
  },
  [Move.RazorWind]: {
    accuracy: 100,
    basePower: 80,
    category: MoveCategory.Special,
    name: "Razor Wind",
    pp: 10,
    priority: 0,
    type: Type.Normal,
    description: "Charges on first turn, attacks on second. High crit ratio.",
  },
  [Move.Recover]: {
    accuracy: null,
    basePower: null,
    category: MoveCategory.Status,
    name: "Recover",
    pp: 10,
    priority: 0,
    type: Type.Normal,
    description: "Restores 1/2 of the user's max HP.",
  },
  [Move.Recycle]: {
    accuracy: null,
    basePower: null,
    category: MoveCategory.Status,
    name: "Recycle",
    pp: 10,
    priority: 0,
    type: Type.Normal,
    description: "Restores the user's held item.",
  },
  [Move.Reflect]: {
    accuracy: null,
    basePower: null,
    category: MoveCategory.Status,
    name: "Reflect",
    pp: 20,
    priority: 0,
    type: Type.Psychic,
    description: "Halves damage from Physical attacks for 5 turns.",
  },
  [Move.Refresh]: {
    accuracy: null,
    basePower: null,
    category: MoveCategory.Status,
    name: "Refresh",
    pp: 20,
    priority: 0,
    type: Type.Normal,
    description: "Cures the user of poison, burns, and paralysis.",
  },
  [Move.Rest]: {
    accuracy: null,
    basePower: null,
    category: MoveCategory.Status,
    name: "Rest",
    pp: 10,
    priority: 0,
    type: Type.Psychic,
    description: "User sleeps for two turns, completely healing itself.",
  },
  [Move.Revenge]: {
    accuracy: 100,
    basePower: 60,
    category: MoveCategory.Physical,
    name: "Revenge",
    pp: 10,
    priority: -4,
    type: Type.Fighting,
    description: "Power doubles if the user was attacked first.",
  },
  [Move.Roar]: {
    accuracy: null,
    basePower: null,
    category: MoveCategory.Status,
    name: "Roar",
    pp: 20,
    priority: -6,
    type: Type.Normal,
    description:
      "The target is forced to switch out and be replaced with a random ally.",
  },
  [Move.RockBlast]: {
    accuracy: 90,
    basePower: 25,
    category: MoveCategory.Physical,
    name: "Rock Blast",
    pp: 10,
    priority: 0,
    type: Type.Rock,
    description: "Hits 2-5 times in one turn.",
  },
  [Move.RockSlide]: {
    accuracy: 90,
    basePower: 75,
    category: MoveCategory.Physical,
    name: "Rock Slide",
    pp: 10,
    priority: 0,
    type: Type.Rock,
    description: "Has a 30% chance to make the target flinch.",
  },
  [Move.RockThrow]: {
    accuracy: 90,
    basePower: 50,
    category: MoveCategory.Physical,
    name: "Rock Throw",
    pp: 15,
    priority: 0,
    type: Type.Rock,
    description: "No additional effect.",
  },
  [Move.RockTomb]: {
    accuracy: 80,
    basePower: 50,
    category: MoveCategory.Physical,
    name: "Rock Tomb",
    pp: 10,
    priority: 0,
    type: Type.Rock,
    description: "Has a 100% chance to lower the target's Speed by one stage.",
  },
  [Move.RolePlay]: {
    accuracy: null,
    basePower: null,
    category: MoveCategory.Status,
    name: "Role Play",
    pp: 10,
    priority: 0,
    type: Type.Psychic,
    description: "The user copies the target's Ability.",
  },
  [Move.RollingKick]: {
    accuracy: 85,
    basePower: 60,
    category: MoveCategory.Physical,
    name: "Rolling Kick",
    pp: 15,
    priority: 0,
    type: Type.Fighting,
    description: "Has a 30% chance to make the target flinch.",
  },
  [Move.SandAttack]: {
    accuracy: 100,
    basePower: null,
    category: MoveCategory.Status,
    name: "Sand Attack",
    pp: 15,
    priority: 0,
    type: Type.Ground,
    description: "Lowers the target's Accuracy by one stage.",
  },
  [Move.SandTomb]: {
    accuracy: 85,
    basePower: 35,
    category: MoveCategory.Physical,
    name: "Sand Tomb",
    pp: 15,
    priority: 0,
    type: Type.Ground,
    description: "Traps the target for 4-5 turns.",
  },
  [Move.Scratch]: {
    accuracy: 100,
    basePower: 40,
    category: MoveCategory.Physical,
    name: "Scratch",
    pp: 35,
    priority: 0,
    type: Type.Normal,
    description: "No additional effect.",
  },
  [Move.Screech]: {
    accuracy: 85,
    basePower: null,
    category: MoveCategory.Status,
    name: "Screech",
    pp: 40,
    priority: 0,
    type: Type.Normal,
    description: "Lowers the target's Defense by two stages.",
  },
  [Move.SecretPower]: {
    accuracy: 100,
    basePower: 70,
    category: MoveCategory.Physical,
    name: "Secret Power",
    pp: 20,
    priority: 0,
    type: Type.Normal,
    description:
      "Has a 30% chance of inflicting a special effect which depends upon the terrain.",
  },
  [Move.SeismicToss]: {
    accuracy: 100,
    basePower: null,
    category: MoveCategory.Physical,
    name: "Seismic Toss",
    pp: 20,
    priority: 0,
    type: Type.Fighting,
    description: "Inflicts damage equal to the user's level.",
  },
  [Move.SelfDestruct]: {
    accuracy: 100,
    basePower: 200,
    category: MoveCategory.Physical,
    name: "Self-Destruct",
    pp: 5,
    priority: 0,
    type: Type.Normal,
    description: "User faints.",
  },
  [Move.ShadowPunch]: {
    accuracy: null,
    basePower: 60,
    category: MoveCategory.Physical,
    name: "Shadow Punch",
    pp: 20,
    priority: 0,
    type: Type.Ghost,
    description: "Ignores accuracy and evasion modifiers.",
  },
  [Move.Sharpen]: {
    accuracy: null,
    basePower: null,
    category: MoveCategory.Status,
    name: "Sharpen",
    pp: 30,
    priority: 0,
    type: Type.Normal,
    description: "Raises the user's Attack by one stage.",
  },
  [Move.Sing]: {
    accuracy: 55,
    basePower: null,
    category: MoveCategory.Status,
    name: "Sing",
    pp: 15,
    priority: 0,
    type: Type.Normal,
    description: "Puts the target to sleep.",
  },
  [Move.SheerCold]: {
    accuracy: 30,
    basePower: null,
    category: MoveCategory.Special,
    name: "Sheer Cold",
    pp: 5,
    priority: 0,
    type: Type.Ice,
    description: "OHKOs the target.",
  },
  [Move.ShockWave]: {
    accuracy: null,
    basePower: 60,
    category: MoveCategory.Special,
    name: "Shock Wave",
    pp: 20,
    priority: 0,
    type: Type.Electric,
    description: "Ignores accuracy and evasion modifiers.",
  },
  [Move.SignalBeam]: {
    accuracy: 100,
    basePower: 75,
    category: MoveCategory.Special,
    name: "Signal Beam",
    pp: 15,
    priority: 0,
    type: Type.Bug,
    description: "Has a 10% chance to confuse the target.",
  },
  [Move.SilverWind]: {
    accuracy: 100,
    basePower: 60,
    category: MoveCategory.Special,
    name: "Silver Wind",
    pp: 5,
    priority: 0,
    type: Type.Bug,
    description:
      "Has a 10% chance to raise all of the user's stats by one stage.",
  },
  [Move.SkillSwap]: {
    accuracy: null,
    basePower: null,
    category: MoveCategory.Status,
    name: "Skill Swap",
    pp: 10,
    priority: 0,
    type: Type.Psychic,
    description: "The user swaps Abilities with the target.",
  },
  [Move.SkullBash]: {
    accuracy: 100,
    basePower: 130,
    category: MoveCategory.Physical,
    name: "Skull Bash",
    pp: 10,
    priority: 0,
    type: Type.Normal,
    description:
      "Raises the user's Defense by one stage. User charges for one turn before attacking.",
  },
  [Move.SkyAttack]: {
    accuracy: 90,
    basePower: 140,
    category: MoveCategory.Physical,
    name: "Sky Attack",
    pp: 5,
    priority: 0,
    type: Type.Flying,
    description: "Charges on first turn, attacks on second. High crit ratio.",
  },
  [Move.SkyUppercut]: {
    accuracy: 90,
    basePower: 85,
    category: MoveCategory.Physical,
    name: "Sky Uppercut",
    pp: 15,
    priority: 0,
    type: Type.Fighting,
    description:
      "Cannot miss against a target that is in the middle of a two-turn move.",
  },
  [Move.SlackOff]: {
    accuracy: null,
    basePower: null,
    category: MoveCategory.Status,
    name: "Slack Off",
    pp: 10,
    priority: 0,
    type: Type.Normal,
    description: "Restores 1/2 of the user's max HP.",
  },
  [Move.Slam]: {
    accuracy: 75,
    basePower: 80,
    category: MoveCategory.Physical,
    name: "Slam",
    pp: 20,
    priority: 0,
    type: Type.Normal,
    description: "No additional effect.",
  },
  [Move.Slash]: {
    accuracy: 100,
    basePower: 70,
    category: MoveCategory.Physical,
    name: "Slash",
    pp: 20,
    priority: 0,
    type: Type.Normal,
    description: "High critical hit ratio.",
  },
  [Move.SleepPowder]: {
    accuracy: 75,
    basePower: null,
    category: MoveCategory.Status,
    name: "Sleep Powder",
    pp: 15,
    priority: 0,
    type: Type.Grass,
    description: "Puts the target to sleep.",
  },
  [Move.Sludge]: {
    accuracy: 100,
    basePower: 65,
    category: MoveCategory.Special,
    name: "Sludge",
    pp: 20,
    priority: 0,
    type: Type.Poison,
    description: "Has a 30% chance to poison the target.",
  },
  [Move.SmellingSalts]: {
    accuracy: 100,
    basePower: 60,
    category: MoveCategory.Physical,
    name: "Smelling Salts",
    pp: 10,
    priority: 0,
    type: Type.Normal,
    description: "Power doubles if the target is paralyzed, but cures it.",
  },
  [Move.Smog]: {
    accuracy: 70,
    basePower: 30,
    category: MoveCategory.Special,
    name: "Smog",
    pp: 20,
    priority: 0,
    type: Type.Poison,
    description: "Has a 40% chance to poison the target.",
  },
  [Move.Smokescreen]: {
    accuracy: 100,
    basePower: null,
    category: MoveCategory.Status,
    name: "Smokescreen",
    pp: 20,
    priority: 0,
    type: Type.Normal,
    description: "Lowers the target's Accuracy by one stage.",
  },
  [Move.Snatch]: {
    accuracy: null,
    basePower: null,
    category: MoveCategory.Status,
    name: "Snatch",
    pp: 10,
    priority: 4,
    type: Type.Dark,
    description: "Steals the effects of the target's next move.",
  },
  [Move.SoftBoiled]: {
    accuracy: null,
    basePower: null,
    category: MoveCategory.Status,
    name: "Soft-Boiled",
    pp: 10,
    priority: 0,
    type: Type.Normal,
    description: "Restores 1/2 of the user's max HP.",
  },
  [Move.SolarBeam]: {
    accuracy: 100,
    basePower: 120,
    category: MoveCategory.Special,
    name: "Solar Beam",
    pp: 10,
    priority: 0,
    type: Type.Grass,
    description: "Charges on first turn, attacks on second.",
  },
  [Move.SonicBoom]: {
    accuracy: 90,
    basePower: null,
    category: MoveCategory.Special,
    name: "Sonic Boom",
    pp: 20,
    priority: 0,
    type: Type.Normal,
    description: "Always inflicts 20 HP.",
  },
  [Move.SpikeCannon]: {
    accuracy: 100,
    basePower: 20,
    category: MoveCategory.Physical,
    name: "Spike Cannon",
    pp: 15,
    priority: 0,
    type: Type.Normal,
    description: "Hits 2-5 times in one turn.",
  },
  [Move.SpitUp]: {
    accuracy: 100,
    basePower: null,
    category: MoveCategory.Special,
    name: "Spit Up",
    pp: 10,
    priority: 0,
    type: Type.Normal,
    description:
      "Power is equal to 100 times the number of times the user has Stockpiled.",
  },
  [Move.Splash]: {
    accuracy: null,
    basePower: null,
    category: MoveCategory.Status,
    name: "Splash",
    pp: 40,
    priority: 0,
    type: Type.Normal,
    description: "Does absolutely nothing.",
  },
  [Move.Spore]: {
    accuracy: 100,
    basePower: null,
    category: MoveCategory.Status,
    name: "Spore",
    pp: 15,
    priority: 0,
    type: Type.Grass,
    description: "Puts the target to sleep.",
  },
  [Move.Stomp]: {
    accuracy: 100,
    basePower: 65,
    category: MoveCategory.Physical,
    name: "Stomp",
    pp: 20,
    priority: 0,
    type: Type.Normal,
    description: "Has a 30% chance to make the target flinch.",
  },
  [Move.Stockpile]: {
    accuracy: null,
    basePower: null,
    category: MoveCategory.Status,
    name: "Stockpile",
    pp: 20,
    priority: 0,
    type: Type.Normal,
    description: "Raises the user's Defense and Special Defense by one stage.",
  },
  [Move.Strength]: {
    accuracy: 100,
    basePower: 80,
    category: MoveCategory.Physical,
    name: "Strength",
    pp: 15,
    priority: 0,
    type: Type.Normal,
    description: "No additional effect.",
  },
  [Move.StringShot]: {
    accuracy: 95,
    basePower: null,
    category: MoveCategory.Status,
    name: "String Shot",
    pp: 40,
    priority: 0,
    type: Type.Bug,
    description: "Lowers the target's Speed by one stage.",
  },
  [Move.Struggle]: {
    accuracy: null,
    basePower: 50,
    category: MoveCategory.Physical,
    name: "Struggle",
    pp: 1,
    priority: 0,
    type: Type.Normal,
    description: "User takes 1/4 recoil damage.",
  },
  [Move.StunSpore]: {
    accuracy: 75,
    basePower: null,
    category: MoveCategory.Status,
    name: "Stun Spore",
    pp: 30,
    priority: 0,
    type: Type.Grass,
    description: "Paralyzes the target.",
  },
  [Move.Submission]: {
    accuracy: 80,
    basePower: 80,
    category: MoveCategory.Physical,
    name: "Submission",
    pp: 25,
    priority: 0,
    type: Type.Fighting,
    description: "User takes 1/4 recoil damage.",
  },
  [Move.Substitute]: {
    accuracy: null,
    basePower: null,
    category: MoveCategory.Status,
    name: "Substitute",
    pp: 10,
    priority: 0,
    type: Type.Normal,
    description:
      "Uses 1/4 of the user's max HP to make a substitute that takes damage for it.",
  },
  [Move.SuperFang]: {
    accuracy: 90,
    basePower: null,
    category: MoveCategory.Physical,
    name: "Super Fang",
    pp: 10,
    priority: 0,
    type: Type.Normal,
    description: "Inflicts damage equal to half the target's HP.",
  },
  [Move.Superpower]: {
    accuracy: 100,
    basePower: 120,
    category: MoveCategory.Physical,
    name: "Superpower",
    pp: 5,
    priority: 0,
    type: Type.Fighting,
    description: "Lowers the user's Attack and Defense by one stage each.",
  },
  [Move.Supersonic]: {
    accuracy: 55,
    basePower: null,
    category: MoveCategory.Status,
    name: "Supersonic",
    pp: 20,
    priority: 0,
    type: Type.Normal,
    description: "Confuses the target.",
  },
  [Move.Surf]: {
    accuracy: 100,
    basePower: 90,
    category: MoveCategory.Special,
    name: "Surf",
    pp: 15,
    priority: 0,
    type: Type.Water,
    description: "Hits all adjacent Pokémon.",
  },
  [Move.Swallow]: {
    accuracy: null,
    basePower: null,
    category: MoveCategory.Status,
    name: "Swallow",
    pp: 10,
    priority: 0,
    type: Type.Normal,
    description:
      "Restores HP based on the number of times the user has Stockpiled.",
  },
  [Move.Swift]: {
    accuracy: null,
    basePower: 60,
    category: MoveCategory.Special,
    name: "Swift",
    pp: 20,
    priority: 0,
    type: Type.Normal,
    description: "Ignores accuracy and evasion modifiers.",
  },
  [Move.SwordsDance]: {
    accuracy: null,
    basePower: null,
    category: MoveCategory.Status,
    name: "Swords Dance",
    pp: 20,
    priority: 0,
    type: Type.Normal,
    description: "Raises the user's Attack by two stages.",
  },
  [Move.Tackle]: {
    accuracy: 100,
    basePower: 40,
    category: MoveCategory.Physical,
    name: "Tackle",
    pp: 35,
    priority: 0,
    type: Type.Normal,
    description: "No additional effect.",
  },
  [Move.TailGlow]: {
    accuracy: null,
    basePower: null,
    category: MoveCategory.Status,
    name: "Tail Glow",
    pp: 20,
    priority: 0,
    type: Type.Bug,
    description: "Raises the user's Special Attack by three stages.",
  },
  [Move.TailWhip]: {
    accuracy: 100,
    basePower: null,
    category: MoveCategory.Status,
    name: "Tail Whip",
    pp: 30,
    priority: 0,
    type: Type.Normal,
    description: "Lowers the target's Defense by one stage.",
  },
  [Move.TakeDown]: {
    accuracy: 85,
    basePower: 90,
    category: MoveCategory.Physical,
    name: "Take Down",
    pp: 20,
    priority: 0,
    type: Type.Normal,
    description: "User takes 1/4 recoil damage.",
  },
  [Move.Taunt]: {
    accuracy: 100,
    basePower: null,
    category: MoveCategory.Status,
    name: "Taunt",
    pp: 20,
    priority: 0,
    type: Type.Dark,
    description:
      "For the next few turns, the target can only use damaging moves.",
  },
  [Move.TeeterDance]: {
    accuracy: 100,
    basePower: null,
    category: MoveCategory.Status,
    name: "Teeter Dance",
    pp: 20,
    priority: 0,
    type: Type.Normal,
    description: "Confuses all Pokémon that are on the field.",
  },
  [Move.Teleport]: {
    accuracy: null,
    basePower: null,
    category: MoveCategory.Status,
    name: "Teleport",
    pp: 20,
    priority: 0,
    type: Type.Psychic,
    description: "Allows the user to flee from battle.",
  },
  [Move.Thrash]: {
    accuracy: 100,
    basePower: 120,
    category: MoveCategory.Physical,
    name: "Thrash",
    pp: 10,
    priority: 0,
    type: Type.Normal,
    description: "User attacks for 2-3 turns but then becomes confused.",
  },
  [Move.Thunder]: {
    accuracy: 70,
    basePower: 110,
    category: MoveCategory.Special,
    name: "Thunder",
    pp: 10,
    priority: 0,
    type: Type.Electric,
    description:
      "Has a 30% chance to paralyze the target. Can hit Pokémon using Bounce or Fly.",
  },
  [Move.ThunderPunch]: {
    accuracy: 100,
    basePower: 75,
    category: MoveCategory.Physical,
    name: "Thunder Punch",
    pp: 15,
    priority: 0,
    type: Type.Electric,
    description: "Has a 10% chance to paralyze the target.",
  },
  [Move.ThunderShock]: {
    accuracy: 100,
    basePower: 40,
    category: MoveCategory.Special,
    name: "Thunder Shock",
    pp: 30,
    priority: 0,
    type: Type.Electric,
    description: "Has a 10% chance to paralyze the target.",
  },
  [Move.ThunderWave]: {
    accuracy: 100,
    basePower: null,
    category: MoveCategory.Status,
    name: "Thunder Wave",
    pp: 20,
    priority: 0,
    type: Type.Electric,
    description: "Paralyzes the target.",
  },
  [Move.Thunderbolt]: {
    accuracy: 100,
    basePower: 90,
    category: MoveCategory.Special,
    name: "Thunderbolt",
    pp: 15,
    priority: 0,
    type: Type.Electric,
    description: "Has a 10% chance to paralyze the target.",
  },
  [Move.Tickle]: {
    accuracy: 100,
    basePower: null,
    category: MoveCategory.Status,
    name: "Tickle",
    pp: 20,
    priority: 0,
    type: Type.Normal,
    description: "Lowers the target's Attack and Defense by one stage.",
  },
  [Move.Torment]: {
    accuracy: 100,
    basePower: null,
    category: MoveCategory.Status,
    name: "Torment",
    pp: 15,
    priority: 0,
    type: Type.Dark,
    description: "The target can only use the same move twice in a row.",
  },
  [Move.Toxic]: {
    accuracy: 90,
    basePower: null,
    category: MoveCategory.Status,
    name: "Toxic",
    pp: 10,
    priority: 0,
    type: Type.Poison,
    description: "Badly poisons the target.",
  },
  [Move.Transform]: {
    accuracy: null,
    basePower: null,
    category: MoveCategory.Status,
    name: "Transform",
    pp: 10,
    priority: 0,
    type: Type.Normal,
    description: "The user transforms into a copy of the target.",
  },
  [Move.Trick]: {
    accuracy: 100,
    basePower: null,
    category: MoveCategory.Status,
    name: "Trick",
    pp: 10,
    priority: 0,
    type: Type.Psychic,
    description: "The user and the target swap held items.",
  },
  [Move.TriAttack]: {
    accuracy: 100,
    basePower: 80,
    category: MoveCategory.Special,
    name: "Tri Attack",
    pp: 10,
    priority: 0,
    type: Type.Normal,
    description: "Has a 20% chance to burn, freeze, or paralyze the target.",
  },
  [Move.Twineedle]: {
    accuracy: 100,
    basePower: 25,
    category: MoveCategory.Physical,
    name: "Twineedle",
    pp: 20,
    priority: 0,
    type: Type.Bug,
    description:
      "Hits twice in one turn. Has a 20% chance to poison the target.",
  },
  [Move.Uproar]: {
    accuracy: 100,
    basePower: 90,
    category: MoveCategory.Special,
    name: "Uproar",
    pp: 10,
    priority: 0,
    type: Type.Normal,
    description: "The user attacks for 3 turns and prevents sleep.",
  },
  [Move.VineWhip]: {
    accuracy: 100,
    basePower: 45,
    category: MoveCategory.Physical,
    name: "Vine Whip",
    pp: 25,
    priority: 0,
    type: Type.Grass,
    description: "No additional effect.",
  },
  [Move.ViseGrip]: {
    accuracy: 100,
    basePower: 55,
    category: MoveCategory.Physical,
    name: "Vise Grip",
    pp: 30,
    priority: 0,
    type: Type.Normal,
    description: "No additional effect.",
  },
  [Move.VoltTackle]: {
    accuracy: 100,
    basePower: 120,
    category: MoveCategory.Physical,
    name: "Volt Tackle",
    pp: 15,
    priority: 0,
    type: Type.Electric,
    description: "User takes 1/3 recoil damage.",
  },
  [Move.WaterGun]: {
    accuracy: 100,
    basePower: 40,
    category: MoveCategory.Special,
    name: "Water Gun",
    pp: 25,
    priority: 0,
    type: Type.Water,
    description: "No additional effect.",
  },
  [Move.WaterPulse]: {
    accuracy: 100,
    basePower: 60,
    category: MoveCategory.Special,
    name: "Water Pulse",
    pp: 20,
    priority: 0,
    type: Type.Water,
    description: "Has a 20% chance to confuse the target.",
  },
  [Move.WaterSport]: {
    accuracy: null,
    basePower: null,
    category: MoveCategory.Status,
    name: "Water Sport",
    pp: 15,
    priority: 0,
    type: Type.Water,
    description:
      "Weakens Fire-type attacks to 1/3 their power during this turn.",
  },
  [Move.WaterSpout]: {
    accuracy: 100,
    basePower: null,
    category: MoveCategory.Special,
    name: "Water Spout",
    pp: 5,
    priority: 0,
    type: Type.Water,
    description: "The lower the user's HP, the lower the move's power.",
  },
  [Move.Waterfall]: {
    accuracy: 100,
    basePower: 80,
    category: MoveCategory.Physical,
    name: "Waterfall",
    pp: 15,
    priority: 0,
    type: Type.Water,
    description: "Has a 20% chance to flinch the target.",
  },
  [Move.WeatherBall]: {
    accuracy: 100,
    basePower: 50,
    category: MoveCategory.Special,
    name: "Weather Ball",
    pp: 10,
    priority: 0,
    type: Type.Normal,
    description: "Power doubles during weather effects.",
  },
  [Move.Whirlwind]: {
    accuracy: null,
    basePower: null,
    category: MoveCategory.Status,
    name: "Whirlwind",
    pp: 20,
    priority: -6,
    type: Type.Normal,
    description:
      "The target is forced to switch out and be replaced with a random ally.",
  },
  [Move.WillOWisp]: {
    accuracy: 75,
    basePower: null,
    category: MoveCategory.Status,
    name: "Will-O-Wisp",
    pp: 15,
    priority: 0,
    type: Type.Fire,
    description: "Burns the target.",
  },
  [Move.WingAttack]: {
    accuracy: 100,
    basePower: 60,
    category: MoveCategory.Physical,
    name: "Wing Attack",
    pp: 35,
    priority: 0,
    type: Type.Flying,
    description: "No additional effect.",
  },
  [Move.Wish]: {
    accuracy: null,
    basePower: null,
    category: MoveCategory.Status,
    name: "Wish",
    pp: 10,
    priority: 0,
    type: Type.Normal,
    description:
      "At the end of the next turn, the Pokémon at the user's position has its HP restored by up to half of its max HP.",
  },
  [Move.Withdraw]: {
    accuracy: null,
    basePower: null,
    category: MoveCategory.Status,
    name: "Withdraw",
    pp: 40,
    priority: 0,
    type: Type.Water,
    description: "Raises the user's Defense by one stage.",
  },
  [Move.Wrap]: {
    accuracy: 90,
    basePower: 15,
    category: MoveCategory.Physical,
    name: "Wrap",
    pp: 20,
    priority: 0,
    type: Type.Normal,
    description: "Traps the target for 4-5 turns.",
  },
  [Move.Yawn]: {
    accuracy: null,
    basePower: null,
    category: MoveCategory.Status,
    name: "Yawn",
    pp: 10,
    priority: 0,
    type: Type.Normal,
    description: "Puts the target to sleep after 1 turn.",
  },
};
