export type BasePokemon = {
  id: number;
  name: string;
  img_front: string;
  img_back: string;
  type: string[];
  height: string;
  weight: string;
  abilities: string[];
  experience: number;
  weaknesses?: string[];
  next_evolution?: {
    id: number;
    name: string;
  }[];
  prev_evolution?: {
    id: number;
    name: string;
  }[];
  stats: {
    hp: number;
    attack: number;
    defense: number;
    sp_attack: number;
    sp_defense: number;
    speed: number;
  };
};

export const pokemons: BasePokemon[] = [
  {
    id: 1,
    name: "Bulbasaur",
    img_front: "pokemon_1_front.png",
    img_back: "pokemon_1_back.png",
    type: ["Grass", "Poison"],
    height: "0.71 m",
    weight: "6.9 kg",

    weaknesses: ["Fire", "Ice", "Flying", "Psychic"],
    abilities: ["Overgrow", "Chlorophyll"],
    experience: 64,
    stats: {
      hp: 45,
      attack: 49,
      defense: 49,
      sp_attack: 65,
      sp_defense: 65,
      speed: 45,
    },
    next_evolution: [
      {
        id: 2,
        name: "Ivysaur",
      },
      {
        id: 3,
        name: "Venusaur",
      },
    ],
  },
  {
    id: 2,
    name: "Ivysaur",
    img_front: "pokemon_2_front.png",
    img_back: "pokemon_2_back.png",
    type: ["Grass", "Poison"],
    height: "0.99 m",
    weight: "13.0 kg",

    weaknesses: ["Fire", "Ice", "Flying", "Psychic"],
    abilities: ["Overgrow", "Chlorophyll"],
    experience: 142,
    stats: {
      hp: 60,
      attack: 62,
      defense: 63,
      sp_attack: 80,
      sp_defense: 80,
      speed: 60,
    },
    prev_evolution: [
      {
        id: 1,
        name: "Bulbasaur",
      },
    ],
    next_evolution: [
      {
        id: 3,
        name: "Venusaur",
      },
    ],
  },
  {
    id: 3,
    name: "Venusaur",
    img_front: "pokemon_3_front.png",
    img_back: "pokemon_3_back.png",
    type: ["Grass", "Poison"],
    height: "2.01 m",
    weight: "100.0 kg",

    abilities: ["Overgrow", "Chlorophyll"],
    experience: 236,
    stats: {
      hp: 80,
      attack: 82,
      defense: 83,
      sp_attack: 100,
      sp_defense: 100,
      speed: 80,
    },
    prev_evolution: [
      {
        id: 1,
        name: "Bulbasaur",
      },
      {
        id: 2,
        name: "Ivysaur",
      },
    ],
  },
  {
    id: 4,
    name: "Charmander",
    img_front: "pokemon_4_front.png",
    img_back: "pokemon_4_back.png",
    type: ["Fire"],
    height: "0.61 m",
    weight: "8.5 kg",

    weaknesses: ["Water", "Ground", "Rock"],
    abilities: ["Blaze", "Solar Power"],
    experience: 62,
    stats: {
      hp: 39,
      attack: 52,
      defense: 43,
      sp_attack: 60,
      sp_defense: 50,
      speed: 65,
    },
    next_evolution: [
      {
        id: 5,
        name: "Charmeleon",
      },
      {
        id: 6,
        name: "Charizard",
      },
    ],
  },
  {
    id: 5,
    name: "Charmeleon",
    img_front: "pokemon_5_front.png",
    img_back: "pokemon_5_back.png",
    type: ["Fire"],
    height: "1.09 m",
    weight: "19.0 kg",

    weaknesses: ["Water", "Ground", "Rock"],
    abilities: ["Blaze", "Solar Power"],
    experience: 142,
    stats: {
      hp: 58,
      attack: 64,
      defense: 58,
      sp_attack: 80,
      sp_defense: 65,
      speed: 80,
    },
    prev_evolution: [
      {
        id: 4,
        name: "Charmander",
      },
    ],
    next_evolution: [
      {
        id: 6,
        name: "Charizard",
      },
    ],
  },
  {
    id: 6,
    name: "Charizard",
    img_front: "pokemon_6_front.png",
    img_back: "pokemon_6_back.png",
    type: ["Fire", "Flying"],
    height: "1.70 m",
    weight: "90.5 kg",

    abilities: ["Blaze", "Solar Power"],
    experience: 240,
    stats: {
      hp: 78,
      attack: 84,
      defense: 78,
      sp_attack: 109,
      sp_defense: 85,
      speed: 100,
    },
    prev_evolution: [
      {
        id: 4,
        name: "Charmander",
      },
      {
        id: 5,
        name: "Charmeleon",
      },
    ],
  },
  {
    id: 7,
    name: "Squirtle",
    img_front: "pokemon_7_front.png",
    img_back: "pokemon_7_back.png",
    type: ["Water"],
    height: "0.51 m",
    weight: "9.0 kg",

    weaknesses: ["Electric", "Grass"],
    abilities: ["Torrent", "Rain Dish"],
    experience: 63,
    stats: {
      hp: 44,
      attack: 48,
      defense: 65,
      sp_attack: 50,
      sp_defense: 64,
      speed: 43,
    },
    next_evolution: [
      {
        id: 8,
        name: "Wartortle",
      },
      {
        id: 9,
        name: "Blastoise",
      },
    ],
  },
  {
    id: 8,
    name: "Wartortle",
    img_front: "pokemon_8_front.png",
    img_back: "pokemon_8_back.png",
    type: ["Water"],
    height: "0.99 m",
    weight: "22.5 kg",

    weaknesses: ["Electric", "Grass"],
    abilities: ["Torrent", "Rain Dish"],
    experience: 142,
    stats: {
      hp: 59,
      attack: 63,
      defense: 80,
      sp_attack: 65,
      sp_defense: 80,
      speed: 58,
    },
    prev_evolution: [
      {
        id: 7,
        name: "Squirtle",
      },
    ],
    next_evolution: [
      {
        id: 9,
        name: "Blastoise",
      },
    ],
  },
  {
    id: 9,
    name: "Blastoise",
    img_front: "pokemon_9_front.png",
    img_back: "pokemon_9_back.png",
    type: ["Water"],
    height: "1.60 m",
    weight: "85.5 kg",

    abilities: ["Torrent", "Rain Dish"],
    experience: 239,
    stats: {
      hp: 79,
      attack: 83,
      defense: 100,
      sp_attack: 85,
      sp_defense: 105,
      speed: 78,
    },
    prev_evolution: [
      {
        id: 7,
        name: "Squirtle",
      },
      {
        id: 8,
        name: "Wartortle",
      },
    ],
  },
  {
    id: 10,
    name: "Caterpie",
    img_front: "pokemon_10_front.png",
    img_back: "pokemon_10_back.png",
    type: ["Bug"],
    height: "0.30 m",
    weight: "2.9 kg",

    weaknesses: ["Fire", "Flying", "Rock"],
    abilities: ["Shield Dust", "Run Away"],
    experience: 39,
    stats: {
      hp: 45,
      attack: 30,
      defense: 35,
      sp_attack: 20,
      sp_defense: 20,
      speed: 45,
    },
    next_evolution: [
      {
        id: 11,
        name: "Metapod",
      },
      {
        id: 12,
        name: "Butterfree",
      },
    ],
  },
  {
    id: 11,
    name: "Metapod",
    img_front: "pokemon_11_front.png",
    img_back: "pokemon_11_back.png",
    type: ["Bug"],
    height: "0.71 m",
    weight: "9.9 kg",

    weaknesses: ["Fire", "Flying", "Rock"],
    abilities: ["Shed Skin"],
    experience: 72,
    stats: {
      hp: 50,
      attack: 20,
      defense: 55,
      sp_attack: 25,
      sp_defense: 25,
      speed: 30,
    },
    prev_evolution: [
      {
        id: 10,
        name: "Caterpie",
      },
    ],
    next_evolution: [
      {
        id: 12,
        name: "Butterfree",
      },
    ],
  },
  {
    id: 12,
    name: "Butterfree",
    img_front: "pokemon_12_front.png",
    img_back: "pokemon_12_back.png",
    type: ["Bug", "Flying"],
    height: "1.09 m",
    weight: "32.0 kg",

    abilities: ["Compound Eyes", "Tinted Lens"],
    experience: 178,
    stats: {
      hp: 60,
      attack: 45,
      defense: 50,
      sp_attack: 90,
      sp_defense: 80,
      speed: 70,
    },
    prev_evolution: [
      {
        id: 10,
        name: "Caterpie",
      },
      {
        id: 11,
        name: "Metapod",
      },
    ],
  },
  {
    id: 13,
    name: "Weedle",
    img_front: "pokemon_13_front.png",
    img_back: "pokemon_13_back.png",
    type: ["Bug", "Poison"],
    height: "0.30 m",
    weight: "3.2 kg",

    weaknesses: ["Fire", "Flying", "Psychic", "Rock"],
    abilities: ["Shield Dust", "Run Away"],
    experience: 39,
    stats: {
      hp: 40,
      attack: 35,
      defense: 30,
      sp_attack: 20,
      sp_defense: 20,
      speed: 50,
    },
    next_evolution: [
      {
        id: 14,
        name: "Kakuna",
      },
      {
        id: 15,
        name: "Beedrill",
      },
    ],
  },
  {
    id: 14,
    name: "Kakuna",
    img_front: "pokemon_14_front.png",
    img_back: "pokemon_14_back.png",
    type: ["Bug", "Poison"],
    height: "0.61 m",
    weight: "10.0 kg",

    weaknesses: ["Fire", "Flying", "Psychic", "Rock"],
    abilities: ["Shed Skin"],
    experience: 72,
    stats: {
      hp: 45,
      attack: 25,
      defense: 50,
      sp_attack: 25,
      sp_defense: 25,
      speed: 35,
    },
    prev_evolution: [
      {
        id: 13,
        name: "Weedle",
      },
    ],
    next_evolution: [
      {
        id: 15,
        name: "Beedrill",
      },
    ],
  },
  {
    id: 15,
    name: "Beedrill",
    img_front: "pokemon_15_front.png",
    img_back: "pokemon_15_back.png",
    type: ["Bug", "Poison"],
    height: "0.99 m",
    weight: "29.5 kg",

    abilities: ["Swarm"],
    experience: 178,
    stats: {
      hp: 65,
      attack: 90,
      defense: 40,
      sp_attack: 45,
      sp_defense: 80,
      speed: 75,
    },
    prev_evolution: [
      {
        id: 13,
        name: "Weedle",
      },
      {
        id: 14,
        name: "Kakuna",
      },
    ],
  },
  {
    id: 16,
    name: "Pidgey",
    img_front: "pokemon_16_front.png",
    img_back: "pokemon_16_back.png",
    type: ["Normal", "Flying"],
    height: "0.30 m",
    weight: "1.8 kg",

    weaknesses: ["Electric", "Rock"],
    abilities: ["Keen Eye", "Tangled Feet", "Big Pecks"],
    experience: 50,
    stats: {
      hp: 40,
      attack: 45,
      defense: 40,
      sp_attack: 35,
      sp_defense: 35,
      speed: 56,
    },
    next_evolution: [
      {
        id: 17,
        name: "Pidgeotto",
      },
      {
        id: 18,
        name: "Pidgeot",
      },
    ],
  },
  {
    id: 17,
    name: "Pidgeotto",
    img_front: "pokemon_17_front.png",
    img_back: "pokemon_17_back.png",
    type: ["Normal", "Flying"],
    height: "1.09 m",
    weight: "30.0 kg",

    weaknesses: ["Electric", "Rock"],
    abilities: ["Keen Eye", "Tangled Feet", "Big Pecks"],
    experience: 122,
    stats: {
      hp: 63,
      attack: 60,
      defense: 55,
      sp_attack: 50,
      sp_defense: 50,
      speed: 71,
    },
    prev_evolution: [
      {
        id: 16,
        name: "Pidgey",
      },
    ],
    next_evolution: [
      {
        id: 18,
        name: "Pidgeot",
      },
    ],
  },
  {
    id: 18,
    name: "Pidgeot",
    img_front: "pokemon_18_front.png",
    img_back: "pokemon_18_back.png",
    type: ["Normal", "Flying"],
    height: "1.50 m",
    weight: "39.5 kg",

    abilities: ["Keen Eye", "Tangled Feet", "Big Pecks"],
    experience: 216,
    stats: {
      hp: 83,
      attack: 80,
      defense: 75,
      sp_attack: 70,
      sp_defense: 70,
      speed: 101,
    },
    prev_evolution: [
      {
        id: 16,
        name: "Pidgey",
      },
      {
        id: 17,
        name: "Pidgeotto",
      },
    ],
  },
  {
    id: 19,
    name: "Rattata",
    img_front: "pokemon_19_front.png",
    img_back: "pokemon_19_back.png",
    type: ["Normal"],
    height: "0.30 m",
    weight: "3.5 kg",

    weaknesses: ["Fighting"],
    abilities: ["Run Away", "Guts", "Hustle", "Gluttony", "Hustle"],
    experience: 51,
    stats: {
      hp: 30,
      attack: 56,
      defense: 35,
      sp_attack: 25,
      sp_defense: 35,
      speed: 72,
    },
    next_evolution: [
      {
        id: 20,
        name: "Raticate",
      },
    ],
  },
  {
    id: 20,
    name: "Raticate",
    img_front: "pokemon_20_front.png",
    img_back: "pokemon_20_back.png",
    type: ["Normal"],
    height: "0.71 m",
    weight: "18.5 kg",

    abilities: ["Run Away", "Guts", "Hustle", "Gluttony", "Hustle"],
    experience: 145,
    stats: {
      hp: 55,
      attack: 81,
      defense: 60,
      sp_attack: 50,
      sp_defense: 70,
      speed: 97,
    },
    prev_evolution: [
      {
        id: 19,
        name: "Rattata",
      },
    ],
  },
  {
    id: 21,
    name: "Spearow",
    img_front: "pokemon_21_front.png",
    img_back: "pokemon_21_back.png",
    type: ["Normal", "Flying"],
    height: "0.30 m",
    weight: "2.0 kg",

    weaknesses: ["Electric", "Rock"],
    abilities: ["Keen Eye", "Sniper"],
    experience: 52,
    stats: {
      hp: 40,
      attack: 60,
      defense: 30,
      sp_attack: 31,
      sp_defense: 31,
      speed: 70,
    },
    next_evolution: [
      {
        id: 22,
        name: "Fearow",
      },
    ],
  },
  {
    id: 22,
    name: "Fearow",
    img_front: "pokemon_22_front.png",
    img_back: "pokemon_22_back.png",
    type: ["Normal", "Flying"],
    height: "1.19 m",
    weight: "38.0 kg",

    abilities: ["Keen Eye", "Sniper"],
    experience: 155,
    stats: {
      hp: 65,
      attack: 90,
      defense: 65,
      sp_attack: 61,
      sp_defense: 61,
      speed: 100,
    },
    prev_evolution: [
      {
        id: 21,
        name: "Spearow",
      },
    ],
  },
  {
    id: 23,
    name: "Ekans",
    img_front: "pokemon_23_front.png",
    img_back: "pokemon_23_back.png",
    type: ["Poison"],
    height: "2.01 m",
    weight: "6.9 kg",

    weaknesses: ["Ground", "Psychic"],
    abilities: ["Intimidate", "Shed Skin", "Unnerve"],
    experience: 58,
    stats: {
      hp: 35,
      attack: 60,
      defense: 44,
      sp_attack: 40,
      sp_defense: 54,
      speed: 55,
    },
    next_evolution: [
      {
        id: 24,
        name: "Arbok",
      },
    ],
  },
  {
    id: 24,
    name: "Arbok",
    img_front: "pokemon_24_front.png",
    img_back: "pokemon_24_back.png",
    type: ["Poison"],
    height: "3.51 m",
    weight: "65.0 kg",

    abilities: ["Intimidate", "Shed Skin", "Unnerve"],
    experience: 157,
    stats: {
      hp: 60,
      attack: 85,
      defense: 69,
      sp_attack: 65,
      sp_defense: 79,
      speed: 80,
    },
    prev_evolution: [
      {
        id: 23,
        name: "Ekans",
      },
    ],
  },
  {
    id: 25,
    name: "Pikachu",
    img_front: "pokemon_25_front.png",
    img_back: "pokemon_25_back.png",
    type: ["Electric"],
    height: "0.41 m",
    weight: "6.0 kg",

    weaknesses: ["Ground"],
    abilities: ["Static"],
    experience: 112,
    stats: {
      hp: 35,
      attack: 55,
      defense: 40,
      sp_attack: 50,
      sp_defense: 50,
      speed: 90,
    },
    next_evolution: [
      {
        id: 26,
        name: "Raichu",
      },
    ],
  },
  {
    id: 26,
    name: "Raichu",
    img_front: "pokemon_26_front.png",
    img_back: "pokemon_26_back.png",
    type: ["Electric"],
    height: "0.79 m",
    weight: "30.0 kg",

    abilities: ["Static"],
    experience: 218,
    stats: {
      hp: 60,
      attack: 90,
      defense: 55,
      sp_attack: 90,
      sp_defense: 80,
      speed: 110,
    },
    prev_evolution: [
      {
        id: 25,
        name: "Pikachu",
      },
    ],
  },
  {
    id: 27,
    name: "Sandshrew",
    img_front: "pokemon_27_front.png",
    img_back: "pokemon_27_back.png",
    type: ["Ground"],
    height: "0.61 m",
    weight: "12.0 kg",

    weaknesses: ["Water", "Grass", "Ice"],
    abilities: ["Sand Veil", "Sand Rush", "Sand Force"],
    experience: 60,
    stats: {
      hp: 50,
      attack: 75,
      defense: 85,
      sp_attack: 20,
      sp_defense: 30,
      speed: 40,
    },
    next_evolution: [
      {
        id: 28,
        name: "Sandslash",
      },
    ],
  },
  {
    id: 28,
    name: "Sandslash",
    img_front: "pokemon_28_front.png",
    img_back: "pokemon_28_back.png",
    type: ["Ground"],
    height: "0.99 m",
    weight: "29.5 kg",

    abilities: ["Sand Veil", "Sand Rush", "Sand Force"],
    experience: 158,
    stats: {
      hp: 75,
      attack: 100,
      defense: 110,
      sp_attack: 45,
      sp_defense: 55,
      speed: 65,
    },
    prev_evolution: [
      {
        id: 27,
        name: "Sandshrew",
      },
    ],
  },
  {
    id: 29,
    name: "Nidoran ♀",
    img_front: "pokemon_29_front.png",
    img_back: "pokemon_29_back.png",
    type: ["Poison"],
    height: "0.41 m",
    weight: "7.0 kg",

    weaknesses: ["Ground", "Psychic"],
    abilities: ["Poison Point", "Rivalry", "Hustle"],
    experience: 55,
    stats: {
      hp: 55,
      attack: 47,
      defense: 52,
      sp_attack: 40,
      sp_defense: 40,
      speed: 41,
    },
    next_evolution: [
      {
        id: 30,
        name: "Nidorina",
      },
      {
        id: 31,
        name: "Nidoqueen",
      },
    ],
  },
  {
    id: 30,
    name: "Nidorina",
    img_front: "pokemon_30_front.png",
    img_back: "pokemon_30_back.png",
    type: ["Poison"],
    height: "0.79 m",
    weight: "20.0 kg",

    weaknesses: ["Ground", "Psychic"],
    abilities: ["Poison Point", "Rivalry", "Hustle"],
    experience: 128,
    stats: {
      hp: 70,
      attack: 62,
      defense: 67,
      sp_attack: 55,
      sp_defense: 55,
      speed: 56,
    },
    prev_evolution: [
      {
        id: 29,
        name: "Nidoran(Female)",
      },
    ],
    next_evolution: [
      {
        id: 31,
        name: "Nidoqueen",
      },
    ],
  },
  {
    id: 31,
    name: "Nidoqueen",
    img_front: "pokemon_31_front.png",
    img_back: "pokemon_31_back.png",
    type: ["Poison", "Ground"],
    height: "1.30 m",
    weight: "60.0 kg",

    abilities: ["Poison Point", "Rivalry", "Sheer Force"],
    experience: 223,
    stats: {
      hp: 90,
      attack: 92,
      defense: 87,
      sp_attack: 75,
      sp_defense: 85,
      speed: 76,
    },
    prev_evolution: [
      {
        id: 29,
        name: "Nidoran(Female)",
      },
      {
        id: 30,
        name: "Nidorina",
      },
    ],
  },
  {
    id: 32,
    name: "Nidoran ♂",
    img_front: "pokemon_32_front.png",
    img_back: "pokemon_32_back.png",
    type: ["Poison"],
    height: "0.51 m",
    weight: "9.0 kg",

    weaknesses: ["Ground", "Psychic"],
    abilities: ["Poison Point", "Rivalry", "Hustle"],
    experience: 55,
    stats: {
      hp: 46,
      attack: 57,
      defense: 40,
      sp_attack: 40,
      sp_defense: 40,
      speed: 50,
    },
    next_evolution: [
      {
        id: 33,
        name: "Nidorino",
      },
      {
        id: 34,
        name: "Nidoking",
      },
    ],
  },
  {
    id: 33,
    name: "Nidorino",
    img_front: "pokemon_33_front.png",
    img_back: "pokemon_33_back.png",
    type: ["Poison"],
    height: "0.89 m",
    weight: "19.5 kg",

    weaknesses: ["Ground", "Psychic"],
    abilities: ["Poison Point", "Rivalry", "Hustle"],
    experience: 128,
    stats: {
      hp: 61,
      attack: 72,
      defense: 57,
      sp_attack: 55,
      sp_defense: 55,
      speed: 65,
    },
    prev_evolution: [
      {
        id: 32,
        name: "Nidoran(Male)",
      },
    ],
    next_evolution: [
      {
        id: 34,
        name: "Nidoking",
      },
    ],
  },
  {
    id: 34,
    name: "Nidoking",
    img_front: "pokemon_34_front.png",
    img_back: "pokemon_34_back.png",
    type: ["Poison", "Ground"],
    height: "1.40 m",
    weight: "62.0 kg",

    abilities: ["Poison Point", "Rivalry", "Sheer Force"],
    experience: 223,
    stats: {
      hp: 81,
      attack: 102,
      defense: 77,
      sp_attack: 85,
      sp_defense: 75,
      speed: 85,
    },
    prev_evolution: [
      {
        id: 32,
        name: "Nidoran(Male)",
      },
      {
        id: 33,
        name: "Nidorino",
      },
    ],
  },
  {
    id: 35,
    name: "Clefairy",
    img_front: "pokemon_35_front.png",
    img_back: "pokemon_35_back.png",
    type: ["Normal"],
    height: "0.61 m",
    weight: "7.5 kg",

    weaknesses: ["Fighting"],
    abilities: ["Cute Charm", "Magic Guard", "Friend Guard"],
    experience: 113,
    stats: {
      hp: 70,
      attack: 45,
      defense: 48,
      sp_attack: 60,
      sp_defense: 65,
      speed: 35,
    },
    next_evolution: [
      {
        id: 36,
        name: "Clefable",
      },
    ],
  },
  {
    id: 36,
    name: "Clefable",
    img_front: "pokemon_36_front.png",
    img_back: "pokemon_36_back.png",
    type: ["Normal"],
    height: "1.30 m",
    weight: "40.0 kg",

    abilities: ["Cute Charm", "Magic Guard", "Unaware"],
    experience: 217,
    stats: {
      hp: 95,
      attack: 70,
      defense: 73,
      sp_attack: 95,
      sp_defense: 90,
      speed: 60,
    },
    prev_evolution: [
      {
        id: 35,
        name: "Clefairy",
      },
    ],
  },
  {
    id: 37,
    name: "Vulpix",
    img_front: "pokemon_37_front.png",
    img_back: "pokemon_37_back.png",
    type: ["Fire"],
    height: "0.61 m",
    weight: "9.9 kg",

    weaknesses: ["Water", "Ground", "Rock"],
    abilities: ["Flash Fire", "Drought"],
    experience: 60,
    stats: {
      hp: 38,
      attack: 41,
      defense: 40,
      sp_attack: 50,
      sp_defense: 65,
      speed: 65,
    },
    next_evolution: [
      {
        id: 38,
        name: "Ninetales",
      },
    ],
  },
  {
    id: 38,
    name: "Ninetales",
    img_front: "pokemon_38_front.png",
    img_back: "pokemon_38_back.png",
    type: ["Fire"],
    height: "1.09 m",
    weight: "19.9 kg",

    abilities: ["Flash Fire", "Drought"],
    experience: 177,
    stats: {
      hp: 73,
      attack: 76,
      defense: 75,
      sp_attack: 81,
      sp_defense: 100,
      speed: 100,
    },
    prev_evolution: [
      {
        id: 37,
        name: "Vulpix",
      },
    ],
  },
  {
    id: 39,
    name: "Jigglypuff",
    img_front: "pokemon_39_front.png",
    img_back: "pokemon_39_back.png",
    type: ["Normal"],
    height: "0.51 m",
    weight: "5.5 kg",

    weaknesses: ["Fighting"],
    abilities: ["Cute Charm", "Competitive", "Friend Guard"],
    experience: 95,
    stats: {
      hp: 115,
      attack: 45,
      defense: 20,
      sp_attack: 45,
      sp_defense: 25,
      speed: 20,
    },
    next_evolution: [
      {
        id: 40,
        name: "Wigglytuff",
      },
    ],
  },
  {
    id: 40,
    name: "Wigglytuff",
    img_front: "pokemon_40_front.png",
    img_back: "pokemon_40_back.png",
    type: ["Normal"],
    height: "0.99 m",
    weight: "12.0 kg",

    abilities: ["Cute Charm", "Competitive", "Frisk"],
    experience: 196,
    stats: {
      hp: 140,
      attack: 70,
      defense: 45,
      sp_attack: 85,
      sp_defense: 50,
      speed: 45,
    },
    prev_evolution: [
      {
        id: 39,
        name: "Jigglypuff",
      },
    ],
  },
  {
    id: 41,
    name: "Zubat",
    img_front: "pokemon_41_front.png",
    img_back: "pokemon_41_back.png",
    type: ["Poison", "Flying"],
    height: "0.79 m",
    weight: "7.5 kg",

    weaknesses: ["Electric", "Ice", "Psychic", "Rock"],
    abilities: ["Inner Focus"],
    experience: 49,
    stats: {
      hp: 40,
      attack: 45,
      defense: 35,
      sp_attack: 30,
      sp_defense: 40,
      speed: 55,
    },
    next_evolution: [
      {
        id: 42,
        name: "Golbat",
      },
    ],
  },
  {
    id: 42,
    name: "Golbat",
    img_front: "pokemon_42_front.png",
    img_back: "pokemon_42_back.png",
    type: ["Poison", "Flying"],
    height: "1.60 m",
    weight: "55.0 kg",

    abilities: ["Inner Focus"],
    experience: 159,
    stats: {
      hp: 75,
      attack: 80,
      defense: 70,
      sp_attack: 65,
      sp_defense: 75,
      speed: 90,
    },
    prev_evolution: [
      {
        id: 41,
        name: "Zubat",
      },
    ],
  },
  {
    id: 43,
    name: "Oddish",
    img_front: "pokemon_43_front.png",
    img_back: "pokemon_43_back.png",
    type: ["Grass", "Poison"],
    height: "0.51 m",
    weight: "5.4 kg",

    weaknesses: ["Fire", "Ice", "Flying", "Psychic"],
    abilities: ["Chlorophyll", "Run Away"],
    experience: 64,
    stats: {
      hp: 45,
      attack: 50,
      defense: 55,
      sp_attack: 75,
      sp_defense: 65,
      speed: 30,
    },
    next_evolution: [
      {
        id: 44,
        name: "Gloom",
      },
      {
        id: 45,
        name: "Vileplume",
      },
    ],
  },
  {
    id: 44,
    name: "Gloom",
    img_front: "pokemon_44_front.png",
    img_back: "pokemon_44_back.png",
    type: ["Grass", "Poison"],
    height: "0.79 m",
    weight: "8.6 kg",

    weaknesses: ["Fire", "Ice", "Flying", "Psychic"],
    abilities: ["Chlorophyll", "Stench"],
    experience: 138,
    stats: {
      hp: 60,
      attack: 65,
      defense: 70,
      sp_attack: 85,
      sp_defense: 75,
      speed: 40,
    },
    prev_evolution: [
      {
        id: 43,
        name: "Oddish",
      },
    ],
    next_evolution: [
      {
        id: 45,
        name: "Vileplume",
      },
    ],
  },
  {
    id: 45,
    name: "Vileplume",
    img_front: "pokemon_45_front.png",
    img_back: "pokemon_45_back.png",
    type: ["Grass", "Poison"],
    height: "1.19 m",
    weight: "18.6 kg",

    abilities: ["Chlorophyll", "Effect Spore"],
    experience: 221,
    stats: {
      hp: 75,
      attack: 80,
      defense: 85,
      sp_attack: 110,
      sp_defense: 90,
      speed: 50,
    },
    prev_evolution: [
      {
        id: 43,
        name: "Oddish",
      },
      {
        id: 44,
        name: "Gloom",
      },
    ],
  },
  {
    id: 46,
    name: "Paras",
    img_front: "pokemon_46_front.png",
    img_back: "pokemon_46_back.png",
    type: ["Bug", "Grass"],
    height: "0.30 m",
    weight: "5.4 kg",

    weaknesses: ["Fire", "Ice", "Poison", "Flying", "Bug", "Rock"],
    abilities: ["Effect Spore", "Dry Skin", "Damp"],
    experience: 57,
    stats: {
      hp: 35,
      attack: 70,
      defense: 55,
      sp_attack: 45,
      sp_defense: 55,
      speed: 25,
    },
    next_evolution: [
      {
        id: 47,
        name: "Parasect",
      },
    ],
  },
  {
    id: 47,
    name: "Parasect",
    img_front: "pokemon_47_front.png",
    img_back: "pokemon_47_back.png",
    type: ["Bug", "Grass"],
    height: "0.99 m",
    weight: "29.5 kg",

    abilities: ["Effect Spore", "Dry Skin", "Damp"],
    experience: 142,
    stats: {
      hp: 60,
      attack: 95,
      defense: 80,
      sp_attack: 60,
      sp_defense: 80,
      speed: 30,
    },
    prev_evolution: [
      {
        id: 46,
        name: "Paras",
      },
    ],
  },
  {
    id: 48,
    name: "Venonat",
    img_front: "pokemon_48_front.png",
    img_back: "pokemon_48_back.png",
    type: ["Bug", "Poison"],
    height: "0.99 m",
    weight: "30.0 kg",

    weaknesses: ["Fire", "Flying", "Psychic", "Rock"],
    abilities: ["Compound Eyes", "Tinted Lens"],
    experience: 61,
    stats: {
      hp: 60,
      attack: 55,
      defense: 50,
      sp_attack: 40,
      sp_defense: 55,
      speed: 45,
    },
    next_evolution: [
      {
        id: 49,
        name: "Venomoth",
      },
    ],
  },
  {
    id: 49,
    name: "Venomoth",
    img_front: "pokemon_49_front.png",
    img_back: "pokemon_49_back.png",
    type: ["Bug", "Poison"],
    height: "1.50 m",
    weight: "12.5 kg",

    abilities: ["Shield Dust", "Tinted Lens"],
    experience: 158,
    stats: {
      hp: 70,
      attack: 65,
      defense: 60,
      sp_attack: 90,
      sp_defense: 75,
      speed: 90,
    },
    prev_evolution: [
      {
        id: 48,
        name: "Venonat",
      },
    ],
  },
  {
    id: 50,
    name: "Diglett",
    img_front: "pokemon_50_front.png",
    img_back: "pokemon_50_back.png",
    type: ["Ground"],
    height: "0.20 m",
    weight: "0.8 kg",

    weaknesses: ["Water", "Grass", "Ice"],
    abilities: ["Sand Veil", "Arena Trap", "Sand Force"],
    experience: 53,
    stats: {
      hp: 10,
      attack: 55,
      defense: 25,
      sp_attack: 35,
      sp_defense: 45,
      speed: 95,
    },
    next_evolution: [
      {
        id: 51,
        name: "Dugtrio",
      },
    ],
  },
  {
    id: 51,
    name: "Dugtrio",
    img_front: "pokemon_51_front.png",
    img_back: "pokemon_51_back.png",
    type: ["Ground"],
    height: "0.71 m",
    weight: "33.3 kg",

    abilities: ["Sand Veil", "Arena Trap", "Sand Force"],
    experience: 142,
    stats: {
      hp: 35,
      attack: 100,
      defense: 50,
      sp_attack: 50,
      sp_defense: 70,
      speed: 120,
    },
    prev_evolution: [
      {
        id: 50,
        name: "Diglett",
      },
    ],
  },
  {
    id: 52,
    name: "Meowth",
    img_front: "pokemon_52_front.png",
    img_back: "pokemon_52_back.png",
    type: ["Normal"],
    height: "0.41 m",
    weight: "4.2 kg",

    weaknesses: ["Fighting"],
    abilities: ["Pickup", "Technician", "Unnerve"],
    experience: 58,
    stats: {
      hp: 40,
      attack: 45,
      defense: 35,
      sp_attack: 40,
      sp_defense: 40,
      speed: 90,
    },
    next_evolution: [
      {
        id: 53,
        name: "Persian",
      },
    ],
  },
  {
    id: 53,
    name: "Persian",
    img_front: "pokemon_53_front.png",
    img_back: "pokemon_53_back.png",
    type: ["Normal"],
    height: "0.99 m",
    weight: "32.0 kg",

    abilities: ["Limber", "Technician", "Unnerve"],
    experience: 154,
    stats: {
      hp: 65,
      attack: 70,
      defense: 60,
      sp_attack: 65,
      sp_defense: 65,
      speed: 115,
    },
    prev_evolution: [
      {
        id: 52,
        name: "Meowth",
      },
    ],
  },
  {
    id: 54,
    name: "Psyduck",
    img_front: "pokemon_54_front.png",
    img_back: "pokemon_54_back.png",
    type: ["Water"],
    height: "0.79 m",
    weight: "19.6 kg",

    weaknesses: ["Electric", "Grass"],
    abilities: ["Damp", "Cloud Nine", "Swift Swim"],
    experience: 64,
    stats: {
      hp: 50,
      attack: 52,
      defense: 48,
      sp_attack: 65,
      sp_defense: 50,
      speed: 55,
    },
    next_evolution: [
      {
        id: 55,
        name: "Golduck",
      },
    ],
  },
  {
    id: 55,
    name: "Golduck",
    img_front: "pokemon_55_front.png",
    img_back: "pokemon_55_back.png",
    type: ["Water"],
    height: "1.70 m",
    weight: "76.6 kg",

    abilities: ["Damp", "Cloud Nine", "Swift Swim"],
    experience: 175,
    stats: {
      hp: 80,
      attack: 82,
      defense: 78,
      sp_attack: 95,
      sp_defense: 80,
      speed: 85,
    },
    prev_evolution: [
      {
        id: 54,
        name: "Psyduck",
      },
    ],
  },
  {
    id: 56,
    name: "Mankey",
    img_front: "pokemon_56_front.png",
    img_back: "pokemon_56_back.png",
    type: ["Fighting"],
    height: "0.51 m",
    weight: "28.0 kg",

    weaknesses: ["Flying", "Psychic", "Fairy"],
    abilities: ["Vital Spirit", "Anger Point", "Defiant"],
    experience: 61,
    stats: {
      hp: 40,
      attack: 80,
      defense: 35,
      sp_attack: 35,
      sp_defense: 45,
      speed: 70,
    },
    next_evolution: [
      {
        id: 57,
        name: "Primeape",
      },
    ],
  },
  {
    id: 57,
    name: "Primeape",
    img_front: "pokemon_57_front.png",
    img_back: "pokemon_57_back.png",
    type: ["Fighting"],
    height: "0.99 m",
    weight: "32.0 kg",

    abilities: ["Vital Spirit", "Anger Point", "Defiant"],
    experience: 159,
    stats: {
      hp: 65,
      attack: 105,
      defense: 60,
      sp_attack: 60,
      sp_defense: 70,
      speed: 95,
    },
    prev_evolution: [
      {
        id: 56,
        name: "Mankey",
      },
    ],
  },
  {
    id: 58,
    name: "Growlithe",
    img_front: "pokemon_58_front.png",
    img_back: "pokemon_58_back.png",
    type: ["Fire"],
    height: "0.71 m",
    weight: "19.0 kg",

    weaknesses: ["Water", "Ground", "Rock"],
    abilities: ["Intimidate", "Flash Fire", "Justified"],
    experience: 70,
    stats: {
      hp: 55,
      attack: 70,
      defense: 45,
      sp_attack: 70,
      sp_defense: 50,
      speed: 60,
    },
    next_evolution: [
      {
        id: 59,
        name: "Arcanine",
      },
    ],
  },
  {
    id: 59,
    name: "Arcanine",
    img_front: "pokemon_59_front.png",
    img_back: "pokemon_59_back.png",
    type: ["Fire"],
    height: "1.91 m",
    weight: "155.0 kg",

    abilities: ["Intimidate", "Flash Fire", "Justified"],
    experience: 194,
    stats: {
      hp: 90,
      attack: 110,
      defense: 80,
      sp_attack: 100,
      sp_defense: 80,
      speed: 95,
    },
    prev_evolution: [
      {
        id: 58,
        name: "Growlithe",
      },
    ],
  },
  {
    id: 60,
    name: "Poliwag",
    img_front: "pokemon_60_front.png",
    img_back: "pokemon_60_back.png",
    type: ["Water"],
    height: "0.61 m",
    weight: "12.4 kg",

    weaknesses: ["Electric", "Grass"],
    abilities: ["Water Absorb", "Damp", "Swift Swim"],
    experience: 60,
    stats: {
      hp: 40,
      attack: 50,
      defense: 40,
      sp_attack: 40,
      sp_defense: 40,
      speed: 90,
    },
    next_evolution: [
      {
        id: 61,
        name: "Poliwhirl",
      },
      {
        id: 62,
        name: "Poliwrath",
      },
    ],
  },
  {
    id: 61,
    name: "Poliwhirl",
    img_front: "pokemon_61_front.png",
    img_back: "pokemon_61_back.png",
    type: ["Water"],
    height: "0.99 m",
    weight: "20.0 kg",

    weaknesses: ["Electric", "Grass"],
    abilities: ["Water Absorb", "Damp", "Swift Swim"],
    experience: 135,
    stats: {
      hp: 65,
      attack: 65,
      defense: 65,
      sp_attack: 50,
      sp_defense: 50,
      speed: 90,
    },
    prev_evolution: [
      {
        id: 60,
        name: "Poliwag",
      },
    ],
    next_evolution: [
      {
        id: 62,
        name: "Poliwrath",
      },
    ],
  },
  {
    id: 62,
    name: "Poliwrath",
    img_front: "pokemon_62_front.png",
    img_back: "pokemon_62_back.png",
    type: ["Water", "Fighting"],
    height: "1.30 m",
    weight: "54.0 kg",

    abilities: ["Water Absorb", "Damp", "Swift Swim"],
    experience: 225,
    stats: {
      hp: 90,
      attack: 95,
      defense: 95,
      sp_attack: 70,
      sp_defense: 90,
      speed: 70,
    },
    prev_evolution: [
      {
        id: 60,
        name: "Poliwag",
      },
      {
        id: 61,
        name: "Poliwhirl",
      },
    ],
  },
  {
    id: 63,
    name: "Abra",
    img_front: "pokemon_63_front.png",
    img_back: "pokemon_63_back.png",
    type: ["Psychic"],
    height: "0.89 m",
    weight: "19.5 kg",

    weaknesses: ["Bug", "Ghost", "Dark"],
    abilities: ["Synchronize", "Inner Focus", "Magic Guard"],
    experience: 62,
    stats: {
      hp: 25,
      attack: 20,
      defense: 15,
      sp_attack: 105,
      sp_defense: 55,
      speed: 90,
    },
    next_evolution: [
      {
        id: 64,
        name: "Kadabra",
      },
      {
        id: 65,
        name: "Alakazam",
      },
    ],
  },
  {
    id: 64,
    name: "Kadabra",
    img_front: "pokemon_64_front.png",
    img_back: "pokemon_64_back.png",
    type: ["Psychic"],
    height: "1.30 m",
    weight: "56.5 kg",

    weaknesses: ["Bug", "Ghost", "Dark"],
    abilities: ["Synchronize", "Inner Focus", "Magic Guard"],
    experience: 140,
    stats: {
      hp: 40,
      attack: 35,
      defense: 30,
      sp_attack: 120,
      sp_defense: 70,
      speed: 105,
    },
    prev_evolution: [
      {
        id: 63,
        name: "Abra",
      },
    ],
    next_evolution: [
      {
        id: 65,
        name: "Alakazam",
      },
    ],
  },
  {
    id: 65,
    name: "Alakazam",
    img_front: "pokemon_65_front.png",
    img_back: "pokemon_65_back.png",
    type: ["Psychic"],
    height: "1.50 m",
    weight: "48.0 kg",

    abilities: ["Synchronize", "Inner Focus", "Magic Guard"],
    experience: 221,
    stats: {
      hp: 55,
      attack: 50,
      defense: 45,
      sp_attack: 135,
      sp_defense: 95,
      speed: 120,
    },
    prev_evolution: [
      {
        id: 63,
        name: "Abra",
      },
      {
        id: 64,
        name: "Kadabra",
      },
    ],
  },
  {
    id: 66,
    name: "Machop",
    img_front: "pokemon_66_front.png",
    img_back: "pokemon_66_back.png",
    type: ["Fighting"],
    height: "0.79 m",
    weight: "19.5 kg",

    weaknesses: ["Flying", "Psychic", "Fairy"],
    abilities: ["Guts", "No Guard", "Steadfast"],
    experience: 61,
    stats: {
      hp: 70,
      attack: 80,
      defense: 50,
      sp_attack: 35,
      sp_defense: 35,
      speed: 35,
    },
    next_evolution: [
      {
        id: 67,
        name: "Machoke",
      },
      {
        id: 68,
        name: "Machamp",
      },
    ],
  },
  {
    id: 67,
    name: "Machoke",
    img_front: "pokemon_67_front.png",
    img_back: "pokemon_67_back.png",
    type: ["Fighting"],
    height: "1.50 m",
    weight: "70.5 kg",

    weaknesses: ["Flying", "Psychic", "Fairy"],
    abilities: ["Guts", "No Guard", "Steadfast"],
    experience: 142,
    stats: {
      hp: 80,
      attack: 100,
      defense: 70,
      sp_attack: 50,
      sp_defense: 60,
      speed: 45,
    },
    prev_evolution: [
      {
        id: 66,
        name: "Machop",
      },
    ],
    next_evolution: [
      {
        id: 68,
        name: "Machamp",
      },
    ],
  },
  {
    id: 68,
    name: "Machamp",
    img_front: "pokemon_68_front.png",
    img_back: "pokemon_68_back.png",
    type: ["Fighting"],
    height: "1.60 m",
    weight: "130.0 kg",

    abilities: ["Guts", "No Guard", "Steadfast"],
    experience: 227,
    stats: {
      hp: 90,
      attack: 130,
      defense: 80,
      sp_attack: 65,
      sp_defense: 85,
      speed: 55,
    },
    prev_evolution: [
      {
        id: 66,
        name: "Machop",
      },
      {
        id: 67,
        name: "Machoke",
      },
    ],
  },
  {
    id: 69,
    name: "Bellsprout",
    img_front: "pokemon_69_front.png",
    img_back: "pokemon_69_back.png",
    type: ["Grass", "Poison"],
    height: "0.71 m",
    weight: "4.0 kg",

    weaknesses: ["Fire", "Ice", "Flying", "Psychic"],
    abilities: ["Chlorophyll", "Gluttony"],
    experience: 60,
    stats: {
      hp: 50,
      attack: 75,
      defense: 35,
      sp_attack: 70,
      sp_defense: 30,
      speed: 40,
    },
    next_evolution: [
      {
        id: 70,
        name: "Weepinbell",
      },
      {
        id: 71,
        name: "Victreebel",
      },
    ],
  },
  {
    id: 70,
    name: "Weepinbell",
    img_front: "pokemon_70_front.png",
    img_back: "pokemon_70_back.png",
    type: ["Grass", "Poison"],
    height: "0.99 m",
    weight: "6.4 kg",

    weaknesses: ["Fire", "Ice", "Flying", "Psychic"],
    abilities: ["Chlorophyll", "Gluttony"],
    experience: 137,
    stats: {
      hp: 65,
      attack: 90,
      defense: 50,
      sp_attack: 85,
      sp_defense: 45,
      speed: 55,
    },
    prev_evolution: [
      {
        id: 69,
        name: "Bellsprout",
      },
    ],
    next_evolution: [
      {
        id: 71,
        name: "Victreebel",
      },
    ],
  },
  {
    id: 71,
    name: "Victreebel",
    img_front: "pokemon_71_front.png",
    img_back: "pokemon_71_back.png",
    type: ["Grass", "Poison"],
    height: "1.70 m",
    weight: "15.5 kg",

    abilities: ["Chlorophyll", "Gluttony"],
    experience: 221,
    stats: {
      hp: 80,
      attack: 105,
      defense: 65,
      sp_attack: 100,
      sp_defense: 70,
      speed: 70,
    },
    prev_evolution: [
      {
        id: 69,
        name: "Bellsprout",
      },
      {
        id: 70,
        name: "Weepinbell",
      },
    ],
  },
  {
    id: 72,
    name: "Tentacool",
    img_front: "pokemon_72_front.png",
    img_back: "pokemon_72_back.png",
    type: ["Water", "Poison"],
    height: "0.89 m",
    weight: "45.5 kg",

    weaknesses: ["Electric", "Ground", "Psychic"],
    abilities: ["Clear Body", "Liquid Ooze", "Rain Dish"],
    experience: 67,
    stats: {
      hp: 40,
      attack: 40,
      defense: 35,
      sp_attack: 50,
      sp_defense: 100,
      speed: 70,
    },
    next_evolution: [
      {
        id: 73,
        name: "Tentacruel",
      },
    ],
  },
  {
    id: 73,
    name: "Tentacruel",
    img_front: "pokemon_73_front.png",
    img_back: "pokemon_73_back.png",
    type: ["Water", "Poison"],
    height: "1.60 m",
    weight: "55.0 kg",

    abilities: ["Clear Body", "Liquid Ooze", "Rain Dish"],
    experience: 180,
    stats: {
      hp: 80,
      attack: 70,
      defense: 65,
      sp_attack: 80,
      sp_defense: 120,
      speed: 100,
    },
    prev_evolution: [
      {
        id: 72,
        name: "Tentacool",
      },
    ],
  },
  {
    id: 74,
    name: "Geodude",
    img_front: "pokemon_74_front.png",
    img_back: "pokemon_74_back.png",
    type: ["Rock", "Ground"],
    height: "0.41 m",
    weight: "20.0 kg",

    weaknesses: ["Water", "Grass", "Ice", "Fighting", "Ground", "Steel"],
    abilities: ["Rock Head", "Sturdy", "Sand Veil"],
    experience: 60,
    stats: {
      hp: 40,
      attack: 80,
      defense: 100,
      sp_attack: 30,
      sp_defense: 30,
      speed: 20,
    },
    next_evolution: [
      {
        id: 75,
        name: "Graveler",
      },
      {
        id: 76,
        name: "Golem",
      },
    ],
  },
  {
    id: 75,
    name: "Graveler",
    img_front: "pokemon_75_front.png",
    img_back: "pokemon_75_back.png",
    type: ["Rock", "Ground"],
    height: "0.99 m",
    weight: "105.0 kg",

    weaknesses: ["Water", "Grass", "Ice", "Fighting", "Ground", "Steel"],
    abilities: ["Rock Head", "Sturdy", "Sand Veil"],
    experience: 137,
    stats: {
      hp: 55,
      attack: 95,
      defense: 115,
      sp_attack: 45,
      sp_defense: 45,
      speed: 35,
    },
    prev_evolution: [
      {
        id: 74,
        name: "Geodude",
      },
    ],
    next_evolution: [
      {
        id: 76,
        name: "Golem",
      },
    ],
  },
  {
    id: 76,
    name: "Golem",
    img_front: "pokemon_76_front.png",
    img_back: "pokemon_76_back.png",
    type: ["Rock", "Ground"],
    height: "1.40 m",
    weight: "300.0 kg",

    abilities: ["Rock Head", "Sturdy", "Sand Veil"],
    experience: 223,
    stats: {
      hp: 80,
      attack: 120,
      defense: 130,
      sp_attack: 55,
      sp_defense: 65,
      speed: 45,
    },
    prev_evolution: [
      {
        id: 74,
        name: "Geodude",
      },
      {
        id: 75,
        name: "Graveler",
      },
    ],
  },
  {
    id: 77,
    name: "Ponyta",
    img_front: "pokemon_77_front.png",
    img_back: "pokemon_77_back.png",
    type: ["Fire"],
    height: "0.99 m",
    weight: "30.0 kg",

    weaknesses: ["Water", "Ground", "Rock"],
    abilities: ["Run Away", "Flash Fire", "Flame Body"],
    experience: 82,
    stats: {
      hp: 50,
      attack: 85,
      defense: 55,
      sp_attack: 65,
      sp_defense: 65,
      speed: 90,
    },
    next_evolution: [
      {
        id: 78,
        name: "Rapidash",
      },
    ],
  },
  {
    id: 78,
    name: "Rapidash",
    img_front: "pokemon_78_front.png",
    img_back: "pokemon_78_back.png",
    type: ["Fire"],
    height: "1.70 m",
    weight: "95.0 kg",

    abilities: ["Run Away", "Flash Fire", "Flame Body"],
    experience: 175,
    stats: {
      hp: 65,
      attack: 100,
      defense: 70,
      sp_attack: 80,
      sp_defense: 80,
      speed: 105,
    },
    prev_evolution: [
      {
        id: 77,
        name: "Ponyta",
      },
    ],
  },
  {
    id: 79,
    name: "Slowpoke",
    img_front: "pokemon_79_front.png",
    img_back: "pokemon_79_back.png",
    type: ["Water", "Psychic"],
    height: "1.19 m",
    weight: "36.0 kg",

    weaknesses: ["Electric", "Grass", "Bug", "Ghost", "Dark"],
    abilities: ["Oblivious", "Own Tempo", "Regenerator"],
    experience: 63,
    stats: {
      hp: 90,
      attack: 65,
      defense: 65,
      sp_attack: 40,
      sp_defense: 40,
      speed: 15,
    },
    next_evolution: [
      {
        id: 80,
        name: "Slowbro",
      },
    ],
  },
  {
    id: 80,
    name: "Slowbro",
    img_front: "pokemon_80_front.png",
    img_back: "pokemon_80_back.png",
    type: ["Water", "Psychic"],
    height: "1.60 m",
    weight: "78.5 kg",

    abilities: ["Oblivious", "Own Tempo", "Regenerator"],
    experience: 172,
    stats: {
      hp: 95,
      attack: 75,
      defense: 110,
      sp_attack: 100,
      sp_defense: 80,
      speed: 30,
    },
    prev_evolution: [
      {
        id: 79,
        name: "Slowpoke",
      },
    ],
  },
  {
    id: 81,
    name: "Magnemite",
    img_front: "pokemon_81_front.png",
    img_back: "pokemon_81_back.png",
    type: ["Electric"],
    height: "0.30 m",
    weight: "6.0 kg",

    weaknesses: ["Fire", "Water", "Ground"],
    abilities: ["Magnet Pull", "Sturdy", "Analytic"],
    experience: 65,
    stats: {
      hp: 25,
      attack: 35,
      defense: 70,
      sp_attack: 95,
      sp_defense: 55,
      speed: 45,
    },
    next_evolution: [
      {
        id: 82,
        name: "Magneton",
      },
    ],
  },
  {
    id: 82,
    name: "Magneton",
    img_front: "pokemon_82_front.png",
    img_back: "pokemon_82_back.png",
    type: ["Electric"],
    height: "0.99 m",
    weight: "60.0 kg",

    abilities: ["Magnet Pull", "Sturdy", "Analytic"],
    experience: 163,
    stats: {
      hp: 50,
      attack: 60,
      defense: 95,
      sp_attack: 120,
      sp_defense: 70,
      speed: 70,
    },
    prev_evolution: [
      {
        id: 81,
        name: "Magnemite",
      },
    ],
  },
  {
    id: 83,
    name: "Farfetch'd",
    img_front: "pokemon_83_front.png",
    img_back: "pokemon_83_back.png",
    type: ["Normal", "Flying"],
    height: "0.79 m",
    weight: "15.0 kg",

    abilities: ["Keen Eye", "Inner Focus", "Defiant"],
    experience: 132,
    stats: {
      hp: 52,
      attack: 65,
      defense: 55,
      sp_attack: 58,
      sp_defense: 62,
      speed: 60,
    },
  },
  {
    id: 84,
    name: "Doduo",
    img_front: "pokemon_84_front.png",
    img_back: "pokemon_84_back.png",
    type: ["Normal", "Flying"],
    height: "1.40 m",
    weight: "39.2 kg",

    weaknesses: ["Electric", "Rock"],
    abilities: ["Run Away", "Early Bird", "Tangled Feet"],
    experience: 62,
    stats: {
      hp: 35,
      attack: 85,
      defense: 45,
      sp_attack: 35,
      sp_defense: 35,
      speed: 75,
    },
    next_evolution: [
      {
        id: 85,
        name: "Dodrio",
      },
    ],
  },
  {
    id: 85,
    name: "Dodrio",
    img_front: "pokemon_85_front.png",
    img_back: "pokemon_85_back.png",
    type: ["Normal", "Flying"],
    height: "1.80 m",
    weight: "85.2 kg",

    abilities: ["Run Away", "Early Bird", "Tangled Feet"],
    experience: 165,
    stats: {
      hp: 60,
      attack: 110,
      defense: 70,
      sp_attack: 60,
      sp_defense: 60,
      speed: 110,
    },
    prev_evolution: [
      {
        id: 84,
        name: "Doduo",
      },
    ],
  },
  {
    id: 86,
    name: "Seel",
    img_front: "pokemon_86_front.png",
    img_back: "pokemon_86_back.png",
    type: ["Water"],
    height: "1.09 m",
    weight: "90.0 kg",

    weaknesses: ["Electric", "Grass"],
    abilities: ["Thick Fat", "Hydration", "Ice Body"],
    experience: 65,
    stats: {
      hp: 65,
      attack: 45,
      defense: 55,
      sp_attack: 45,
      sp_defense: 70,
      speed: 45,
    },
    next_evolution: [
      {
        id: 87,
        name: "Dewgong",
      },
    ],
  },
  {
    id: 87,
    name: "Dewgong",
    img_front: "pokemon_87_front.png",
    img_back: "pokemon_87_back.png",
    type: ["Water", "Ice"],
    height: "1.70 m",
    weight: "120.0 kg",

    abilities: ["Thick Fat", "Hydration", "Ice Body"],
    experience: 166,
    stats: {
      hp: 90,
      attack: 70,
      defense: 80,
      sp_attack: 70,
      sp_defense: 95,
      speed: 70,
    },
    prev_evolution: [
      {
        id: 86,
        name: "Seel",
      },
    ],
  },
  {
    id: 88,
    name: "Grimer",
    img_front: "pokemon_88_front.png",
    img_back: "pokemon_88_back.png",
    type: ["Poison"],
    height: "0.89 m",
    weight: "30.0 kg",

    weaknesses: ["Ground", "Psychic"],
    abilities: ["Stench", "Sticky Hold", "Poison Touch"],
    experience: 65,
    stats: {
      hp: 80,
      attack: 80,
      defense: 50,
      sp_attack: 40,
      sp_defense: 50,
      speed: 25,
    },
    next_evolution: [
      {
        id: 89,
        name: "Muk",
      },
    ],
  },
  {
    id: 89,
    name: "Muk",
    img_front: "pokemon_89_front.png",
    img_back: "pokemon_89_back.png",
    type: ["Poison"],
    height: "1.19 m",
    weight: "30.0 kg",

    abilities: ["Stench", "Sticky Hold", "Poison Touch"],
    experience: 175,
    stats: {
      hp: 105,
      attack: 105,
      defense: 75,
      sp_attack: 65,
      sp_defense: 100,
      speed: 50,
    },
    prev_evolution: [
      {
        id: 88,
        name: "Grimer",
      },
    ],
  },
  {
    id: 90,
    name: "Shellder",
    img_front: "pokemon_90_front.png",
    img_back: "pokemon_90_back.png",
    type: ["Water"],
    height: "0.30 m",
    weight: "4.0 kg",

    weaknesses: ["Electric", "Grass"],
    abilities: ["Shell Armor", "Skill Link", "Overcoat"],
    experience: 61,
    stats: {
      hp: 30,
      attack: 65,
      defense: 100,
      sp_attack: 45,
      sp_defense: 25,
      speed: 40,
    },
    next_evolution: [
      {
        id: 91,
        name: "Cloyster",
      },
    ],
  },
  {
    id: 91,
    name: "Cloyster",
    img_front: "pokemon_91_front.png",
    img_back: "pokemon_91_back.png",
    type: ["Water", "Ice"],
    height: "1.50 m",
    weight: "132.5 kg",

    abilities: ["Shell Armor", "Skill Link", "Overcoat"],
    experience: 184,
    stats: {
      hp: 50,
      attack: 95,
      defense: 180,
      sp_attack: 85,
      sp_defense: 45,
      speed: 70,
    },
    prev_evolution: [
      {
        id: 90,
        name: "Shellder",
      },
    ],
  },
  {
    id: 92,
    name: "Gastly",
    img_front: "pokemon_92_front.png",
    img_back: "pokemon_92_back.png",
    type: ["Ghost", "Poison"],
    height: "1.30 m",
    weight: "0.1 kg",

    weaknesses: ["Ground", "Psychic", "Ghost", "Dark"],
    abilities: ["Levitate"],
    experience: 62,
    stats: {
      hp: 30,
      attack: 35,
      defense: 30,
      sp_attack: 100,
      sp_defense: 35,
      speed: 80,
    },
    next_evolution: [
      {
        id: 93,
        name: "Haunter",
      },
      {
        id: 94,
        name: "Gengar",
      },
    ],
  },
  {
    id: 93,
    name: "Haunter",
    img_front: "pokemon_93_front.png",
    img_back: "pokemon_93_back.png",
    type: ["Ghost", "Poison"],
    height: "1.60 m",
    weight: "0.1 kg",

    weaknesses: ["Ground", "Psychic", "Ghost", "Dark"],
    abilities: ["Levitate"],
    experience: 142,
    stats: {
      hp: 45,
      attack: 50,
      defense: 45,
      sp_attack: 115,
      sp_defense: 55,
      speed: 95,
    },
    prev_evolution: [
      {
        id: 92,
        name: "Gastly",
      },
    ],
    next_evolution: [
      {
        id: 94,
        name: "Gengar",
      },
    ],
  },
  {
    id: 94,
    name: "Gengar",
    img_front: "pokemon_94_front.png",
    img_back: "pokemon_94_back.png",
    type: ["Ghost", "Poison"],
    height: "1.50 m",
    weight: "40.5 kg",

    abilities: ["Cursed Body"],
    experience: 225,
    stats: {
      hp: 60,
      attack: 65,
      defense: 60,
      sp_attack: 130,
      sp_defense: 75,
      speed: 110,
    },
    prev_evolution: [
      {
        id: 92,
        name: "Gastly",
      },
      {
        id: 93,
        name: "Haunter",
      },
    ],
  },
  {
    id: 95,
    name: "Onix",
    img_front: "pokemon_95_front.png",
    img_back: "pokemon_95_back.png",
    type: ["Rock", "Ground"],
    height: "8.79 m",
    weight: "210.0 kg",

    abilities: ["Rock Head", "Sturdy", "Weak Armor"],
    experience: 77,
    stats: {
      hp: 35,
      attack: 45,
      defense: 160,
      sp_attack: 30,
      sp_defense: 45,
      speed: 70,
    },
  },
  {
    id: 96,
    name: "Drowzee",
    img_front: "pokemon_96_front.png",
    img_back: "pokemon_96_back.png",
    type: ["Psychic"],
    height: "0.99 m",
    weight: "32.4 kg",

    weaknesses: ["Bug", "Ghost", "Dark"],
    abilities: ["Insomnia", "Forewarn", "Inner Focus"],
    experience: 66,
    stats: {
      hp: 60,
      attack: 48,
      defense: 45,
      sp_attack: 43,
      sp_defense: 90,
      speed: 42,
    },
    next_evolution: [
      {
        id: 97,
        name: "Hypno",
      },
    ],
  },
  {
    id: 97,
    name: "Hypno",
    img_front: "pokemon_97_front.png",
    img_back: "pokemon_97_back.png",
    type: ["Psychic"],
    height: "1.60 m",
    weight: "75.6 kg",

    abilities: ["Insomnia", "Forewarn", "Inner Focus"],
    experience: 169,
    stats: {
      hp: 85,
      attack: 73,
      defense: 70,
      sp_attack: 73,
      sp_defense: 115,
      speed: 67,
    },
    prev_evolution: [
      {
        id: 96,
        name: "Drowzee",
      },
    ],
  },
  {
    id: 98,
    name: "Krabby",
    img_front: "pokemon_98_front.png",
    img_back: "pokemon_98_back.png",
    type: ["Water"],
    height: "0.41 m",
    weight: "6.5 kg",

    weaknesses: ["Electric", "Grass"],
    abilities: ["Hyper Cutter", "Shell Armor", "Sheer Force"],
    experience: 65,
    stats: {
      hp: 30,
      attack: 105,
      defense: 90,
      sp_attack: 25,
      sp_defense: 25,
      speed: 50,
    },
    next_evolution: [
      {
        id: 99,
        name: "Kingler",
      },
    ],
  },
  {
    id: 99,
    name: "Kingler",
    img_front: "pokemon_99_front.png",
    img_back: "pokemon_99_back.png",
    type: ["Water"],
    height: "1.30 m",
    weight: "60.0 kg",

    abilities: ["Hyper Cutter", "Shell Armor", "Sheer Force"],
    experience: 166,
    stats: {
      hp: 55,
      attack: 130,
      defense: 115,
      sp_attack: 50,
      sp_defense: 50,
      speed: 75,
    },
    prev_evolution: [
      {
        id: 98,
        name: "Krabby",
      },
    ],
  },
  {
    id: 100,
    name: "Voltorb",
    img_front: "pokemon_100_front.png",
    img_back: "pokemon_100_back.png",
    type: ["Electric"],
    height: "0.51 m",
    weight: "10.4 kg",

    weaknesses: ["Ground"],
    abilities: ["Soundproof", "Static", "Aftermath"],
    experience: 66,
    stats: {
      hp: 40,
      attack: 30,
      defense: 50,
      sp_attack: 55,
      sp_defense: 55,
      speed: 100,
    },
    next_evolution: [
      {
        id: 101,
        name: "Electrode",
      },
    ],
  },
  {
    id: 101,
    name: "Electrode",
    img_front: "pokemon_101_front.png",
    img_back: "pokemon_101_back.png",
    type: ["Electric"],
    height: "1.19 m",
    weight: "66.6 kg",

    abilities: ["Soundproof", "Static", "Aftermath"],
    experience: 168,
    stats: {
      hp: 60,
      attack: 50,
      defense: 70,
      sp_attack: 80,
      sp_defense: 80,
      speed: 140,
    },
    prev_evolution: [
      {
        id: 100,
        name: "Voltorb",
      },
    ],
  },
  {
    id: 102,
    name: "Exeggcute",
    img_front: "pokemon_102_front.png",
    img_back: "pokemon_102_back.png",
    type: ["Grass", "Psychic"],
    height: "0.41 m",
    weight: "2.5 kg",

    weaknesses: ["Fire", "Ice", "Poison", "Flying", "Bug", "Ghost", "Dark"],
    abilities: ["Chlorophyll", "Harvest"],
    experience: 65,
    stats: {
      hp: 60,
      attack: 40,
      defense: 80,
      sp_attack: 60,
      sp_defense: 45,
      speed: 40,
    },
    next_evolution: [
      {
        id: 103,
        name: "Exeggutor",
      },
    ],
  },
  {
    id: 103,
    name: "Exeggutor",
    img_front: "pokemon_103_front.png",
    img_back: "pokemon_103_back.png",
    type: ["Grass", "Psychic"],
    height: "2.01 m",
    weight: "120.0 kg",

    abilities: ["Chlorophyll", "Harvest"],
    experience: 186,
    stats: {
      hp: 95,
      attack: 95,
      defense: 85,
      sp_attack: 125,
      sp_defense: 65,
      speed: 55,
    },
    prev_evolution: [
      {
        id: 102,
        name: "Exeggcute",
      },
    ],
  },
  {
    id: 104,
    name: "Cubone",
    img_front: "pokemon_104_front.png",
    img_back: "pokemon_104_back.png",
    type: ["Ground"],
    height: "0.41 m",
    weight: "6.5 kg",

    weaknesses: ["Water", "Grass", "Ice"],
    abilities: ["Rock Head", "Lightning Rod", "Battle Armor"],
    experience: 64,
    stats: {
      hp: 50,
      attack: 50,
      defense: 95,
      sp_attack: 40,
      sp_defense: 50,
      speed: 35,
    },
    next_evolution: [
      {
        id: 105,
        name: "Marowak",
      },
    ],
  },
  {
    id: 105,
    name: "Marowak",
    img_front: "pokemon_105_front.png",
    img_back: "pokemon_105_back.png",
    type: ["Ground"],
    height: "0.99 m",
    weight: "45.0 kg",

    abilities: ["Rock Head", "Lightning Rod", "Battle Armor"],
    experience: 149,
    stats: {
      hp: 60,
      attack: 80,
      defense: 110,
      sp_attack: 50,
      sp_defense: 80,
      speed: 45,
    },
    prev_evolution: [
      {
        id: 104,
        name: "Cubone",
      },
    ],
  },
  {
    id: 106,
    name: "Hitmonlee",
    img_front: "pokemon_106_front.png",
    img_back: "pokemon_106_back.png",
    type: ["Fighting"],
    height: "1.50 m",
    weight: "49.8 kg",

    abilities: ["Limber", "Reckless", "Unburden"],
    experience: 159,
    stats: {
      hp: 50,
      attack: 120,
      defense: 53,
      sp_attack: 35,
      sp_defense: 110,
      speed: 87,
    },
  },
  {
    id: 107,
    name: "Hitmonchan",
    img_front: "pokemon_107_front.png",
    img_back: "pokemon_107_back.png",
    type: ["Fighting"],
    height: "1.40 m",
    weight: "50.2 kg",

    abilities: ["Keen Eye", "Iron Fist", "Inner Focus"],
    experience: 159,
    stats: {
      hp: 50,
      attack: 105,
      defense: 79,
      sp_attack: 35,
      sp_defense: 110,
      speed: 76,
    },
  },
  {
    id: 108,
    name: "Lickitung",
    img_front: "pokemon_108_front.png",
    img_back: "pokemon_108_back.png",
    type: ["Normal"],
    height: "1.19 m",
    weight: "65.5 kg",

    abilities: ["Own Tempo", "Oblivious", "Cloud Nine"],
    experience: 77,
    stats: {
      hp: 90,
      attack: 55,
      defense: 75,
      sp_attack: 60,
      sp_defense: 75,
      speed: 30,
    },
  },
  {
    id: 109,
    name: "Koffing",
    img_front: "pokemon_109_front.png",
    img_back: "pokemon_109_back.png",
    type: ["Poison"],
    height: "0.61 m",
    weight: "1.0 kg",

    weaknesses: ["Ground", "Psychic"],
    abilities: ["Levitate"],
    experience: 68,
    stats: {
      hp: 40,
      attack: 65,
      defense: 95,
      sp_attack: 60,
      sp_defense: 45,
      speed: 35,
    },
    next_evolution: [
      {
        id: 110,
        name: "Weezing",
      },
    ],
  },
  {
    id: 110,
    name: "Weezing",
    img_front: "pokemon_110_front.png",
    img_back: "pokemon_110_back.png",
    type: ["Poison"],
    height: "1.19 m",
    weight: "9.5 kg",

    abilities: ["Levitate"],
    experience: 172,
    stats: {
      hp: 65,
      attack: 90,
      defense: 120,
      sp_attack: 85,
      sp_defense: 70,
      speed: 60,
    },
    prev_evolution: [
      {
        id: 109,
        name: "Koffing",
      },
    ],
  },
  {
    id: 111,
    name: "Rhyhorn",
    img_front: "pokemon_111_front.png",
    img_back: "pokemon_111_back.png",
    type: ["Ground", "Rock"],
    height: "0.99 m",
    weight: "115.0 kg",

    weaknesses: ["Water", "Grass", "Ice", "Fighting", "Ground", "Steel"],
    abilities: ["Lightning Rod", "Rock Head", "Reckless"],
    experience: 69,
    stats: {
      hp: 80,
      attack: 85,
      defense: 95,
      sp_attack: 30,
      sp_defense: 30,
      speed: 25,
    },
    next_evolution: [
      {
        id: 112,
        name: "Rhydon",
      },
    ],
  },
  {
    id: 112,
    name: "Rhydon",
    img_front: "pokemon_112_front.png",
    img_back: "pokemon_112_back.png",
    type: ["Ground", "Rock"],
    height: "1.91 m",
    weight: "120.0 kg",

    abilities: ["Lightning Rod", "Rock Head", "Reckless"],
    experience: 170,
    stats: {
      hp: 105,
      attack: 130,
      defense: 120,
      sp_attack: 45,
      sp_defense: 45,
      speed: 40,
    },
    prev_evolution: [
      {
        id: 111,
        name: "Rhyhorn",
      },
    ],
  },
  {
    id: 113,
    name: "Chansey",
    img_front: "pokemon_113_front.png",
    img_back: "pokemon_113_back.png",
    type: ["Normal"],
    height: "1.09 m",
    weight: "34.6 kg",

    abilities: ["Natural Cure", "Serene Grace", "Healer"],
    experience: 395,
    stats: {
      hp: 250,
      attack: 5,
      defense: 5,
      sp_attack: 35,
      sp_defense: 105,
      speed: 50,
    },
  },
  {
    id: 114,
    name: "Tangela",
    img_front: "pokemon_114_front.png",
    img_back: "pokemon_114_back.png",
    type: ["Grass"],
    height: "0.99 m",
    weight: "35.0 kg",

    abilities: ["Chlorophyll", "Leaf Guard", "Regenerator"],
    experience: 87,
    stats: {
      hp: 65,
      attack: 55,
      defense: 115,
      sp_attack: 100,
      sp_defense: 40,
      speed: 60,
    },
  },
  {
    id: 115,
    name: "Kangaskhan",
    img_front: "pokemon_115_front.png",
    img_back: "pokemon_115_back.png",
    type: ["Normal"],
    height: "2.21 m",
    weight: "80.0 kg",

    abilities: ["Early Bird", "Scrappy", "Inner Focus"],
    experience: 172,
    stats: {
      hp: 105,
      attack: 95,
      defense: 80,
      sp_attack: 40,
      sp_defense: 80,
      speed: 90,
    },
  },
  {
    id: 116,
    name: "Horsea",
    img_front: "pokemon_116_front.png",
    img_back: "pokemon_116_back.png",
    type: ["Water"],
    height: "0.41 m",
    weight: "8.0 kg",

    weaknesses: ["Electric", "Grass"],
    abilities: ["Swift Swim", "Sniper"],
    experience: 59,
    stats: {
      hp: 30,
      attack: 40,
      defense: 70,
      sp_attack: 70,
      sp_defense: 25,
      speed: 60,
    },
    next_evolution: [
      {
        id: 117,
        name: "Seadra",
      },
    ],
  },
  {
    id: 117,
    name: "Seadra",
    img_front: "pokemon_117_front.png",
    img_back: "pokemon_117_back.png",
    type: ["Water"],
    height: "1.19 m",
    weight: "25.0 kg",

    abilities: ["Poison Point", "Sniper"],
    experience: 154,
    stats: {
      hp: 55,
      attack: 65,
      defense: 95,
      sp_attack: 95,
      sp_defense: 45,
      speed: 85,
    },
    prev_evolution: [
      {
        id: 116,
        name: "Horsea",
      },
    ],
  },
  {
    id: 118,
    name: "Goldeen",
    img_front: "pokemon_118_front.png",
    img_back: "pokemon_118_back.png",
    type: ["Water"],
    height: "0.61 m",
    weight: "15.0 kg",

    weaknesses: ["Electric", "Grass"],
    abilities: ["Swift Swim", "Water Veil", "Lightning Rod"],
    experience: 64,
    stats: {
      hp: 45,
      attack: 67,
      defense: 60,
      sp_attack: 35,
      sp_defense: 50,
      speed: 63,
    },
    next_evolution: [
      {
        id: 119,
        name: "Seaking",
      },
    ],
  },
  {
    id: 119,
    name: "Seaking",
    img_front: "pokemon_119_front.png",
    img_back: "pokemon_119_back.png",
    type: ["Water"],
    height: "1.30 m",
    weight: "39.0 kg",

    abilities: ["Swift Swim", "Water Veil", "Lightning Rod"],
    experience: 158,
    stats: {
      hp: 80,
      attack: 92,
      defense: 65,
      sp_attack: 65,
      sp_defense: 80,
      speed: 68,
    },
    prev_evolution: [
      {
        id: 118,
        name: "Goldeen",
      },
    ],
  },
  {
    id: 120,
    name: "Staryu",
    img_front: "pokemon_120_front.png",
    img_back: "pokemon_120_back.png",
    type: ["Water"],
    height: "0.79 m",
    weight: "34.5 kg",

    weaknesses: ["Electric", "Grass"],
    abilities: ["Illuminate", "Natural Cure"],
    experience: 68,
    stats: {
      hp: 30,
      attack: 45,
      defense: 55,
      sp_attack: 70,
      sp_defense: 55,
      speed: 85,
    },
    next_evolution: [
      {
        id: 121,
        name: "Starmie",
      },
    ],
  },
  {
    id: 121,
    name: "Starmie",
    img_front: "pokemon_121_front.png",
    img_back: "pokemon_121_back.png",
    type: ["Water", "Psychic"],
    height: "1.09 m",
    weight: "80.0 kg",

    abilities: ["Illuminate", "Natural Cure", "Analytic"],
    experience: 182,
    stats: {
      hp: 60,
      attack: 75,
      defense: 85,
      sp_attack: 100,
      sp_defense: 85,
      speed: 115,
    },
    prev_evolution: [
      {
        id: 120,
        name: "Staryu",
      },
    ],
  },
  {
    id: 122,
    name: "Mr. Mime",
    img_front: "pokemon_122_front.png",
    img_back: "pokemon_122_back.png",
    type: ["Psychic"],
    height: "1.30 m",
    weight: "54.5 kg",

    abilities: ["Soundproof", "Filter", "Technician"],
    experience: 161,
    stats: {
      hp: 40,
      attack: 45,
      defense: 65,
      sp_attack: 100,
      sp_defense: 120,
      speed: 90,
    },
  },
  {
    id: 123,
    name: "Scyther",
    img_front: "pokemon_123_front.png",
    img_back: "pokemon_123_back.png",
    type: ["Bug", "Flying"],
    height: "1.50 m",
    weight: "56.0 kg",

    abilities: ["Swarm", "Technician", "Steadfast"],
    experience: 100,
    stats: {
      hp: 70,
      attack: 110,
      defense: 80,
      sp_attack: 55,
      sp_defense: 80,
      speed: 105,
    },
  },
  {
    id: 124,
    name: "Jynx",
    img_front: "pokemon_124_front.png",
    img_back: "pokemon_124_back.png",
    type: ["Ice", "Psychic"],
    height: "1.40 m",
    weight: "40.6 kg",

    abilities: ["Oblivious", "Forewarn", "Dry Skin"],
    experience: 159,
    stats: {
      hp: 65,
      attack: 50,
      defense: 35,
      sp_attack: 115,
      sp_defense: 95,
      speed: 95,
    },
  },
  {
    id: 125,
    name: "Electabuzz",
    img_front: "pokemon_125_front.png",
    img_back: "pokemon_125_back.png",
    type: ["Electric"],
    height: "1.09 m",
    weight: "30.0 kg",

    abilities: ["Static", "Vital Spirit"],
    experience: 172,
    stats: {
      hp: 65,
      attack: 83,
      defense: 57,
      sp_attack: 95,
      sp_defense: 85,
      speed: 105,
    },
  },
  {
    id: 126,
    name: "Magmar",
    img_front: "pokemon_126_front.png",
    img_back: "pokemon_126_back.png",
    type: ["Fire"],
    height: "1.30 m",
    weight: "44.5 kg",

    abilities: ["Flame Body", "Vital Spirit"],
    experience: 173,
    stats: {
      hp: 65,
      attack: 95,
      defense: 57,
      sp_attack: 100,
      sp_defense: 85,
      speed: 93,
    },
  },
  {
    id: 127,
    name: "Pinsir",
    img_front: "pokemon_127_front.png",
    img_back: "pokemon_127_back.png",
    type: ["Bug"],
    height: "1.50 m",
    weight: "55.0 kg",

    abilities: ["Hyper Cutter", "Mold Breaker", "Moxie"],
    experience: 175,
    stats: {
      hp: 65,
      attack: 125,
      defense: 100,
      sp_attack: 55,
      sp_defense: 70,
      speed: 85,
    },
  },
  {
    id: 128,
    name: "Tauros",
    img_front: "pokemon_128_front.png",
    img_back: "pokemon_128_back.png",
    type: ["Normal"],
    height: "1.40 m",
    weight: "88.4 kg",

    abilities: ["Intimidate", "Anger Point", "Sheer Force"],
    experience: 172,
    stats: {
      hp: 75,
      attack: 100,
      defense: 95,
      sp_attack: 40,
      sp_defense: 70,
      speed: 110,
    },
  },
  {
    id: 129,
    name: "Magikarp",
    img_front: "pokemon_129_front.png",
    img_back: "pokemon_129_back.png",
    type: ["Water"],
    height: "0.89 m",
    weight: "10.0 kg",

    weaknesses: ["Electric", "Grass"],
    abilities: ["Swift Swim", "Rattled"],
    experience: 40,
    stats: {
      hp: 20,
      attack: 10,
      defense: 55,
      sp_attack: 15,
      sp_defense: 20,
      speed: 80,
    },
    next_evolution: [
      {
        id: 130,
        name: "Gyarados",
      },
    ],
  },
  {
    id: 130,
    name: "Gyarados",
    img_front: "pokemon_130_front.png",
    img_back: "pokemon_130_back.png",
    type: ["Water", "Flying"],
    height: "6.50 m",
    weight: "235.0 kg",

    abilities: ["Intimidate"],
    experience: 189,
    stats: {
      hp: 95,
      attack: 125,
      defense: 79,
      sp_attack: 60,
      sp_defense: 100,
      speed: 81,
    },
    prev_evolution: [
      {
        id: 129,
        name: "Magikarp",
      },
    ],
  },
  {
    id: 131,
    name: "Lapras",
    img_front: "pokemon_131_front.png",
    img_back: "pokemon_131_back.png",
    type: ["Water", "Ice"],
    height: "2.49 m",
    weight: "220.0 kg",

    abilities: ["Water Absorb", "Shell Armor", "Hydration"],
    experience: 187,
    stats: {
      hp: 130,
      attack: 85,
      defense: 80,
      sp_attack: 85,
      sp_defense: 95,
      speed: 60,
    },
  },
  {
    id: 132,
    name: "Ditto",
    img_front: "pokemon_132_front.png",
    img_back: "pokemon_132_back.png",
    type: ["Normal"],
    height: "0.30 m",
    weight: "4.0 kg",

    abilities: ["Limber", "Imposter"],
    experience: 101,
    stats: {
      hp: 48,
      attack: 48,
      defense: 48,
      sp_attack: 48,
      sp_defense: 48,
      speed: 48,
    },
  },
  {
    id: 133,
    name: "Eevee",
    img_front: "pokemon_133_front.png",
    img_back: "pokemon_133_back.png",
    type: ["Normal"],
    height: "0.30 m",
    weight: "6.5 kg",

    weaknesses: ["Fighting"],
    abilities: ["Run Away", "Adaptability", "Anticipation"],
    experience: 65,
    stats: {
      hp: 55,
      attack: 55,
      defense: 50,
      sp_attack: 45,
      sp_defense: 65,
      speed: 55,
    },
    next_evolution: [
      {
        id: 134,
        name: "Vaporeon",
      },
      {
        id: 135,
        name: "Jolteon",
      },
      {
        id: 136,
        name: "Flareon",
      },
    ],
  },
  {
    id: 134,
    name: "Vaporeon",
    img_front: "pokemon_134_front.png",
    img_back: "pokemon_134_back.png",
    type: ["Water"],
    height: "0.99 m",
    weight: "29.0 kg",

    abilities: ["Water Absorb", "Hydration"],
    experience: 184,
    stats: {
      hp: 130,
      attack: 65,
      defense: 60,
      sp_attack: 110,
      sp_defense: 95,
      speed: 65,
    },
    prev_evolution: [
      {
        id: 133,
        name: "Eevee",
      },
    ],
  },
  {
    id: 135,
    name: "Jolteon",
    img_front: "pokemon_135_front.png",
    img_back: "pokemon_135_back.png",
    type: ["Electric"],
    height: "0.79 m",
    weight: "24.5 kg",

    abilities: ["Volt Absorb", "Quick Feet"],
    experience: 184,
    stats: {
      hp: 65,
      attack: 65,
      defense: 60,
      sp_attack: 110,
      sp_defense: 95,
      speed: 130,
    },
    prev_evolution: [
      {
        id: 133,
        name: "Eevee",
      },
    ],
  },
  {
    id: 136,
    name: "Flareon",
    img_front: "pokemon_136_front.png",
    img_back: "pokemon_136_back.png",
    type: ["Fire"],
    height: "0.89 m",
    weight: "25.0 kg",

    abilities: ["Flash Fire", "Guts"],
    experience: 184,
    stats: {
      hp: 65,
      attack: 130,
      defense: 60,
      sp_attack: 95,
      sp_defense: 110,
      speed: 65,
    },
    prev_evolution: [
      {
        id: 133,
        name: "Eevee",
      },
    ],
  },
  {
    id: 137,
    name: "Porygon",
    img_front: "pokemon_137_front.png",
    img_back: "pokemon_137_back.png",
    type: ["Normal"],
    height: "0.79 m",
    weight: "36.5 kg",

    abilities: ["Trace", "Download", "Analytic"],
    experience: 79,
    stats: {
      hp: 65,
      attack: 60,
      defense: 70,
      sp_attack: 85,
      sp_defense: 75,
      speed: 40,
    },
  },
  {
    id: 138,
    name: "Omanyte",
    img_front: "pokemon_138_front.png",
    img_back: "pokemon_138_back.png",
    type: ["Rock", "Water"],
    height: "0.41 m",
    weight: "7.5 kg",

    weaknesses: ["Electric", "Grass", "Fighting", "Ground"],
    abilities: ["Swift Swim", "Shell Armor", "Weak Armor"],
    experience: 71,
    stats: {
      hp: 35,
      attack: 40,
      defense: 100,
      sp_attack: 90,
      sp_defense: 55,
      speed: 35,
    },
    next_evolution: [
      {
        id: 139,
        name: "Omastar",
      },
    ],
  },
  {
    id: 139,
    name: "Omastar",
    img_front: "pokemon_139_front.png",
    img_back: "pokemon_139_back.png",
    type: ["Rock", "Water"],
    height: "0.99 m",
    weight: "35.0 kg",

    abilities: ["Swift Swim", "Shell Armor", "Weak Armor"],
    experience: 173,
    stats: {
      hp: 70,
      attack: 60,
      defense: 125,
      sp_attack: 115,
      sp_defense: 70,
      speed: 55,
    },
    prev_evolution: [
      {
        id: 138,
        name: "Omanyte",
      },
    ],
  },
  {
    id: 140,
    name: "Kabuto",
    img_front: "pokemon_140_front.png",
    img_back: "pokemon_140_back.png",
    type: ["Rock", "Water"],
    height: "0.51 m",
    weight: "11.5 kg",

    weaknesses: ["Electric", "Grass", "Fighting", "Ground"],
    abilities: ["Swift Swim", "Battle Armor", "Weak Armor"],
    experience: 71,
    stats: {
      hp: 30,
      attack: 80,
      defense: 90,
      sp_attack: 55,
      sp_defense: 45,
      speed: 55,
    },
    next_evolution: [
      {
        id: 141,
        name: "Kabutops",
      },
    ],
  },
  {
    id: 141,
    name: "Kabutops",
    img_front: "pokemon_141_front.png",
    img_back: "pokemon_141_back.png",
    type: ["Rock", "Water"],
    height: "1.30 m",
    weight: "40.5 kg",

    abilities: ["Swift Swim", "Battle Armor", "Weak Armor"],
    experience: 173,
    stats: {
      hp: 60,
      attack: 115,
      defense: 105,
      sp_attack: 65,
      sp_defense: 70,
      speed: 80,
    },
    prev_evolution: [
      {
        id: 140,
        name: "Kabuto",
      },
    ],
  },
  {
    id: 142,
    name: "Aerodactyl",
    img_front: "pokemon_142_front.png",
    img_back: "pokemon_142_back.png",
    type: ["Rock", "Flying"],
    height: "1.80 m",
    weight: "59.0 kg",

    abilities: ["Rock Head", "Pressure", "Unnerve"],
    experience: 180,
    stats: {
      hp: 80,
      attack: 105,
      defense: 65,
      sp_attack: 60,
      sp_defense: 75,
      speed: 130,
    },
  },
  {
    id: 143,
    name: "Snorlax",
    img_front: "pokemon_143_front.png",
    img_back: "pokemon_143_back.png",
    type: ["Normal"],
    height: "2.11 m",
    weight: "460.0 kg",

    abilities: ["Immunity", "Thick Fat", "Gluttony"],
    experience: 189,
    stats: {
      hp: 160,
      attack: 110,
      defense: 65,
      sp_attack: 65,
      sp_defense: 110,
      speed: 30,
    },
  },
  {
    id: 144,
    name: "Articuno",
    img_front: "pokemon_144_front.png",
    img_back: "pokemon_144_back.png",
    type: ["Ice", "Flying"],
    height: "1.70 m",
    weight: "55.4 kg",

    abilities: ["Pressure", "Snow Cloak"],
    experience: 261,
    stats: {
      hp: 90,
      attack: 85,
      defense: 100,
      sp_attack: 95,
      sp_defense: 125,
      speed: 85,
    },
  },
  {
    id: 145,
    name: "Zapdos",
    img_front: "pokemon_145_front.png",
    img_back: "pokemon_145_back.png",
    type: ["Electric", "Flying"],
    height: "1.60 m",
    weight: "52.6 kg",

    abilities: ["Pressure", "Static"],
    experience: 261,
    stats: {
      hp: 90,
      attack: 90,
      defense: 85,
      sp_attack: 125,
      sp_defense: 90,
      speed: 100,
    },
  },
  {
    id: 146,
    name: "Moltres",
    img_front: "pokemon_146_front.png",
    img_back: "pokemon_146_back.png",
    type: ["Fire", "Flying"],
    height: "2.01 m",
    weight: "60.0 kg",

    abilities: ["Pressure", "Flame Body"],
    experience: 261,
    stats: {
      hp: 90,
      attack: 100,
      defense: 90,
      sp_attack: 125,
      sp_defense: 85,
      speed: 90,
    },
  },
  {
    id: 147,
    name: "Dratini",
    img_front: "pokemon_147_front.png",
    img_back: "pokemon_147_back.png",
    type: ["Dragon"],
    height: "1.80 m",
    weight: "3.3 kg",

    weaknesses: ["Ice", "Dragon", "Fairy"],
    abilities: ["Shed Skin"],
    experience: 60,
    stats: {
      hp: 41,
      attack: 64,
      defense: 45,
      sp_attack: 50,
      sp_defense: 50,
      speed: 50,
    },
    next_evolution: [
      {
        id: 148,
        name: "Dragonair",
      },
      {
        id: 149,
        name: "Dragonite",
      },
    ],
  },
  {
    id: 148,
    name: "Dragonair",
    img_front: "pokemon_148_front.png",
    img_back: "pokemon_148_back.png",
    type: ["Dragon"],
    height: "3.99 m",
    weight: "16.5 kg",

    weaknesses: ["Ice", "Dragon", "Fairy"],
    abilities: ["Shed Skin"],
    experience: 147,
    stats: {
      hp: 61,
      attack: 84,
      defense: 65,
      sp_attack: 70,
      sp_defense: 70,
      speed: 70,
    },
    prev_evolution: [
      {
        id: 147,
        name: "Dratini",
      },
    ],
    next_evolution: [
      {
        id: 149,
        name: "Dragonite",
      },
    ],
  },
  {
    id: 149,
    name: "Dragonite",
    img_front: "pokemon_149_front.png",
    img_back: "pokemon_149_back.png",
    type: ["Dragon", "Flying"],
    height: "2.21 m",
    weight: "210.0 kg",

    abilities: ["Inner Focus", "Multiscale"],
    experience: 270,
    stats: {
      hp: 91,
      attack: 134,
      defense: 95,
      sp_attack: 100,
      sp_defense: 100,
      speed: 80,
    },
    prev_evolution: [
      {
        id: 147,
        name: "Dratini",
      },
      {
        id: 148,
        name: "Dragonair",
      },
    ],
  },
  {
    id: 150,
    name: "Mewtwo",
    img_front: "pokemon_150_front.png",
    img_back: "pokemon_150_back.png",
    type: ["Psychic"],
    height: "2.01 m",
    weight: "122.0 kg",

    abilities: ["Pressure", "Unnerve"],
    experience: 306,
    stats: {
      hp: 106,
      attack: 110,
      defense: 90,
      sp_attack: 154,
      sp_defense: 90,
      speed: 130,
    },
  },
  {
    id: 151,
    name: "Mew",
    img_front: "pokemon_151_front.png",
    img_back: "pokemon_151_back.png",
    type: ["Psychic"],
    height: "0.41 m",
    weight: "4.0 kg",

    abilities: ["Synchronize"],
    experience: 270,
    stats: {
      hp: 100,
      attack: 100,
      defense: 100,
      sp_attack: 100,
      sp_defense: 100,
      speed: 100,
    },
  },
];
